// Code generated by go-enum DO NOT EDIT.
// Version:
// Revision:
// Build Date:
// Built By:

package types

import (
	"fmt"
	"strings"
)

const (
	// ChatContentTypeMd is a ChatContentType of type md.
	// Markdown
	ChatContentTypeMd ChatContentType = "md"
	// ChatContentTypeHtml is a ChatContentType of type html.
	// HTML
	ChatContentTypeHtml ChatContentType = "html"
)

var ErrInvalidChatContentType = fmt.Errorf("not a valid ChatContentType, try [%s]", strings.Join(_ChatContentTypeNames, ", "))

var _ChatContentTypeNames = []string{
	string(ChatContentTypeMd),
	string(ChatContentTypeHtml),
}

// ChatContentTypeNames returns a list of possible string values of ChatContentType.
func ChatContentTypeNames() []string {
	tmp := make([]string, len(_ChatContentTypeNames))
	copy(tmp, _ChatContentTypeNames)
	return tmp
}

// ChatContentTypeValues returns a list of the values for ChatContentType
func ChatContentTypeValues() []ChatContentType {
	return []ChatContentType{
		ChatContentTypeMd,
		ChatContentTypeHtml,
	}
}

// String implements the Stringer interface.
func (x ChatContentType) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x ChatContentType) IsValid() bool {
	_, err := ParseChatContentType(string(x))
	return err == nil
}

var _ChatContentTypeValue = map[string]ChatContentType{
	"md":   ChatContentTypeMd,
	"html": ChatContentTypeHtml,
}

// ParseChatContentType attempts to convert a string to a ChatContentType.
func ParseChatContentType(name string) (ChatContentType, error) {
	if x, ok := _ChatContentTypeValue[name]; ok {
		return x, nil
	}
	return ChatContentType(""), fmt.Errorf("%s is %w", name, ErrInvalidChatContentType)
}

// MustParseChatContentType converts a string to a ChatContentType, and panics if is not valid.
func MustParseChatContentType(name string) ChatContentType {
	val, err := ParseChatContentType(name)
	if err != nil {
		panic(err)
	}
	return val
}

func (x ChatContentType) Ptr() *ChatContentType {
	return &x
}

const (
	// ChatroomRedPacketTypeRandom is a ChatroomRedPacketType of type random.
	// 拼手气红包
	ChatroomRedPacketTypeRandom ChatroomRedPacketType = "random"
	// ChatroomRedPacketTypeAverage is a ChatroomRedPacketType of type average.
	// 平分红包
	ChatroomRedPacketTypeAverage ChatroomRedPacketType = "average"
	// ChatroomRedPacketTypeSpecify is a ChatroomRedPacketType of type specify.
	// 专属红包
	ChatroomRedPacketTypeSpecify ChatroomRedPacketType = "specify"
	// ChatroomRedPacketTypeHeartbeat is a ChatroomRedPacketType of type heartbeat.
	// 心跳红包
	ChatroomRedPacketTypeHeartbeat ChatroomRedPacketType = "heartbeat"
	// ChatroomRedPacketTypeRockPaperScissors is a ChatroomRedPacketType of type rockPaperScissors.
	// 猜拳红包
	ChatroomRedPacketTypeRockPaperScissors ChatroomRedPacketType = "rockPaperScissors"
)

var ErrInvalidChatroomRedPacketType = fmt.Errorf("not a valid ChatroomRedPacketType, try [%s]", strings.Join(_ChatroomRedPacketTypeNames, ", "))

var _ChatroomRedPacketTypeNames = []string{
	string(ChatroomRedPacketTypeRandom),
	string(ChatroomRedPacketTypeAverage),
	string(ChatroomRedPacketTypeSpecify),
	string(ChatroomRedPacketTypeHeartbeat),
	string(ChatroomRedPacketTypeRockPaperScissors),
}

// ChatroomRedPacketTypeNames returns a list of possible string values of ChatroomRedPacketType.
func ChatroomRedPacketTypeNames() []string {
	tmp := make([]string, len(_ChatroomRedPacketTypeNames))
	copy(tmp, _ChatroomRedPacketTypeNames)
	return tmp
}

// ChatroomRedPacketTypeValues returns a list of the values for ChatroomRedPacketType
func ChatroomRedPacketTypeValues() []ChatroomRedPacketType {
	return []ChatroomRedPacketType{
		ChatroomRedPacketTypeRandom,
		ChatroomRedPacketTypeAverage,
		ChatroomRedPacketTypeSpecify,
		ChatroomRedPacketTypeHeartbeat,
		ChatroomRedPacketTypeRockPaperScissors,
	}
}

// String implements the Stringer interface.
func (x ChatroomRedPacketType) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x ChatroomRedPacketType) IsValid() bool {
	_, err := ParseChatroomRedPacketType(string(x))
	return err == nil
}

var _ChatroomRedPacketTypeValue = map[string]ChatroomRedPacketType{
	"random":            ChatroomRedPacketTypeRandom,
	"average":           ChatroomRedPacketTypeAverage,
	"specify":           ChatroomRedPacketTypeSpecify,
	"heartbeat":         ChatroomRedPacketTypeHeartbeat,
	"rockPaperScissors": ChatroomRedPacketTypeRockPaperScissors,
}

// ParseChatroomRedPacketType attempts to convert a string to a ChatroomRedPacketType.
func ParseChatroomRedPacketType(name string) (ChatroomRedPacketType, error) {
	if x, ok := _ChatroomRedPacketTypeValue[name]; ok {
		return x, nil
	}
	return ChatroomRedPacketType(""), fmt.Errorf("%s is %w", name, ErrInvalidChatroomRedPacketType)
}

// MustParseChatroomRedPacketType converts a string to a ChatroomRedPacketType, and panics if is not valid.
func MustParseChatroomRedPacketType(name string) ChatroomRedPacketType {
	val, err := ParseChatroomRedPacketType(name)
	if err != nil {
		panic(err)
	}
	return val
}

func (x ChatroomRedPacketType) Ptr() *ChatroomRedPacketType {
	return &x
}
