// Code generated by go-enum DO NOT EDIT.
// Version:
// Revision:
// Build Date:
// Built By:

package types

import (
	"fmt"
	"strings"
)

const (
	// ClientTypeWeb is a ClientType of type Web.
	ClientTypeWeb ClientType = "Web"
	// ClientTypePC is a ClientType of type PC.
	ClientTypePC ClientType = "PC"
	// ClientTypeMobile is a ClientType of type Mobile.
	ClientTypeMobile ClientType = "Mobile"
	// ClientTypeWindows is a ClientType of type Windows.
	ClientTypeWindows ClientType = "Windows"
	// ClientTypeMacOS is a ClientType of type macOS.
	ClientTypeMacOS ClientType = "macOS"
	// ClientTypeLinux is a ClientType of type Linux.
	ClientTypeLinux ClientType = "Linux"
	// ClientTypeIOS is a ClientType of type iOS.
	ClientTypeIOS ClientType = "iOS"
	// ClientTypeAndroid is a ClientType of type Android.
	ClientTypeAndroid ClientType = "Android"
	// ClientTypeIDEA is a ClientType of type IDEA.
	ClientTypeIDEA ClientType = "IDEA"
	// ClientTypeChrome is a ClientType of type Chrome.
	ClientTypeChrome ClientType = "Chrome"
	// ClientTypeEdge is a ClientType of type Edge.
	ClientTypeEdge ClientType = "Edge"
	// ClientTypeVSCode is a ClientType of type VSCode.
	ClientTypeVSCode ClientType = "VSCode"
	// ClientTypePython is a ClientType of type Python.
	ClientTypePython ClientType = "Python"
	// ClientTypeGolang is a ClientType of type Golang.
	ClientTypeGolang ClientType = "Golang"
	// ClientTypeRust is a ClientType of type Rust.
	ClientTypeRust ClientType = "Rust"
	// ClientTypeHarmony is a ClientType of type Harmony.
	ClientTypeHarmony ClientType = "Harmony"
	// ClientTypeCLI is a ClientType of type CLI.
	ClientTypeCLI ClientType = "CLI"
	// ClientTypeBird is a ClientType of type Bird.
	ClientTypeBird ClientType = "Bird"
	// ClientTypeIceNet is a ClientType of type IceNet.
	ClientTypeIceNet ClientType = "IceNet"
	// ClientTypeElvesOnline is a ClientType of type ElvesOnline.
	ClientTypeElvesOnline ClientType = "ElvesOnline"
	// ClientTypeOther is a ClientType of type Other.
	ClientTypeOther ClientType = "Other"
)

var ErrInvalidClientType = fmt.Errorf("not a valid ClientType, try [%s]", strings.Join(_ClientTypeNames, ", "))

var _ClientTypeNames = []string{
	string(ClientTypeWeb),
	string(ClientTypePC),
	string(ClientTypeMobile),
	string(ClientTypeWindows),
	string(ClientTypeMacOS),
	string(ClientTypeLinux),
	string(ClientTypeIOS),
	string(ClientTypeAndroid),
	string(ClientTypeIDEA),
	string(ClientTypeChrome),
	string(ClientTypeEdge),
	string(ClientTypeVSCode),
	string(ClientTypePython),
	string(ClientTypeGolang),
	string(ClientTypeRust),
	string(ClientTypeHarmony),
	string(ClientTypeCLI),
	string(ClientTypeBird),
	string(ClientTypeIceNet),
	string(ClientTypeElvesOnline),
	string(ClientTypeOther),
}

// ClientTypeNames returns a list of possible string values of ClientType.
func ClientTypeNames() []string {
	tmp := make([]string, len(_ClientTypeNames))
	copy(tmp, _ClientTypeNames)
	return tmp
}

// ClientTypeValues returns a list of the values for ClientType
func ClientTypeValues() []ClientType {
	return []ClientType{
		ClientTypeWeb,
		ClientTypePC,
		ClientTypeMobile,
		ClientTypeWindows,
		ClientTypeMacOS,
		ClientTypeLinux,
		ClientTypeIOS,
		ClientTypeAndroid,
		ClientTypeIDEA,
		ClientTypeChrome,
		ClientTypeEdge,
		ClientTypeVSCode,
		ClientTypePython,
		ClientTypeGolang,
		ClientTypeRust,
		ClientTypeHarmony,
		ClientTypeCLI,
		ClientTypeBird,
		ClientTypeIceNet,
		ClientTypeElvesOnline,
		ClientTypeOther,
	}
}

// String implements the Stringer interface.
func (x ClientType) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x ClientType) IsValid() bool {
	_, err := ParseClientType(string(x))
	return err == nil
}

var _ClientTypeValue = map[string]ClientType{
	"Web":         ClientTypeWeb,
	"PC":          ClientTypePC,
	"Mobile":      ClientTypeMobile,
	"Windows":     ClientTypeWindows,
	"macOS":       ClientTypeMacOS,
	"Linux":       ClientTypeLinux,
	"iOS":         ClientTypeIOS,
	"Android":     ClientTypeAndroid,
	"IDEA":        ClientTypeIDEA,
	"Chrome":      ClientTypeChrome,
	"Edge":        ClientTypeEdge,
	"VSCode":      ClientTypeVSCode,
	"Python":      ClientTypePython,
	"Golang":      ClientTypeGolang,
	"Rust":        ClientTypeRust,
	"Harmony":     ClientTypeHarmony,
	"CLI":         ClientTypeCLI,
	"Bird":        ClientTypeBird,
	"IceNet":      ClientTypeIceNet,
	"ElvesOnline": ClientTypeElvesOnline,
	"Other":       ClientTypeOther,
}

// ParseClientType attempts to convert a string to a ClientType.
func ParseClientType(name string) (ClientType, error) {
	if x, ok := _ClientTypeValue[name]; ok {
		return x, nil
	}
	return ClientType(""), fmt.Errorf("%s is %w", name, ErrInvalidClientType)
}

// MustParseClientType converts a string to a ClientType, and panics if is not valid.
func MustParseClientType(name string) ClientType {
	val, err := ParseClientType(name)
	if err != nil {
		panic(err)
	}
	return val
}

func (x ClientType) Ptr() *ClientType {
	return &x
}

// MarshalText implements the text marshaller method.
func (x ClientType) MarshalText() ([]byte, error) {
	return []byte(string(x)), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *ClientType) UnmarshalText(text []byte) error {
	tmp, err := ParseClientType(string(text))
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}
