// Code generated by go-enum DO NOT EDIT.
// Version:
// Revision:
// Build Date:
// Built By:

package types

import (
	"fmt"
	"strings"
)

const (
	// DataTypeArticle is a DataType of type Article.
	// 文章
	DataTypeArticle DataType = iota
	// DataTypeComment is a DataType of type Comment.
	// 评论
	DataTypeComment
	// DataTypeAt is a DataType of type At.
	// @
	DataTypeAt
	// DataTypeCommented is a DataType of type Commented.
	// 被评论
	DataTypeCommented
	// DataTypeFollowingUser is a DataType of type FollowingUser.
	// 关注用户
	DataTypeFollowingUser
	// DataTypePointCharge is a DataType of type PointCharge.
	// 积分充值
	DataTypePointCharge
	// DataTypePointTransfer is a DataType of type PointTransfer.
	// 积分转账
	DataTypePointTransfer
	// DataTypePointArticleReward is a DataType of type PointArticleReward.
	// 文章打赏
	DataTypePointArticleReward
	// DataTypePointArticleThank is a DataType of type PointArticleThank.
	// 文章感谢
	DataTypePointArticleThank
	// DataTypePointCommentThank is a DataType of type PointCommentThank.
	// 评论感谢
	DataTypePointCommentThank
	// DataTypePointInviteRegister is a DataType of type PointInviteRegister.
	// 邀请注册
	DataTypePointInviteRegister
	// DataTypePointInviteJoinActivation is a DataType of type PointInviteJoinActivation.
	// 邀请加入激活
	DataTypePointInviteJoinActivation
	// DataTypePointPerfectArticle is a DataType of type PointPerfectArticle.
	// 完美文章
	DataTypePointPerfectArticle
	// DataTypePointCommentAccept is a DataType of type PointCommentAccept.
	// 评论采纳
	DataTypePointCommentAccept
	// DataTypePointFollowing is a DataType of type PointFollowing.
	// 关注
	DataTypePointFollowing
	// DataTypePointFollower is a DataType of type PointFollower.
	// 被关注
	DataTypePointFollower
	// DataTypePointExchange is a DataType of type PointExchange.
	// 积分兑换
	DataTypePointExchange
	// DataTypePointAbuseDeduct is a DataType of type PointAbuseDeduct.
	// 滥用扣除
	DataTypePointAbuseDeduct
	// DataTypePointStickArticle is a DataType of type PointStickArticle.
	// 置顶文章
	DataTypePointStickArticle
	// DataTypePointRedPacket is a DataType of type PointRedPacket.
	// 红包
	DataTypePointRedPacket
	// DataTypePointTopArticle is a DataType of type PointTopArticle.
	// 顶帖
	DataTypePointTopArticle
	// DataTypePointReport is a DataType of type PointReport.
	// 举报
	DataTypePointReport
	// DataTypePointRepublishArticle is a DataType of type PointRepublishArticle.
	// 重新发布文章
	DataTypePointRepublishArticle
	// DataTypePointSellerBuyerAdvance is a DataType of type PointSellerBuyerAdvance.
	// 卖家买家预付
	DataTypePointSellerBuyerAdvance
	// DataTypePointCommentVote is a DataType of type PointCommentVote.
	// 评论投票
	DataTypePointCommentVote
	// DataTypePointArticleVote is a DataType of type PointArticleVote.
	// 文章投票
	DataTypePointArticleVote
	// DataTypePointAppeal is a DataType of type PointAppeal.
	// 申诉
	DataTypePointAppeal
	// DataTypePointPurchaseInvitecode is a DataType of type PointPurchaseInvitecode.
	// 购买邀请码
	DataTypePointPurchaseInvitecode
	// DataTypePointForward is a DataType of type PointForward.
	// 转发
	DataTypePointForward
)

var ErrInvalidDataType = fmt.Errorf("not a valid DataType, try [%s]", strings.Join(_DataTypeNames, ", "))

const _DataTypeName = "articlecommentatcommentedfollowingUserpointChargepointTransferpointArticleRewardpointArticleThankpointCommentThankpointInviteRegisterpointInviteJoinActivationpointPerfectArticlepointCommentAcceptpointFollowingpointFollowerpointExchangepointAbuseDeductpointStickArticlepointRedPacketpointTopArticlepointReportpointRepublishArticlepointSellerBuyerAdvancepointCommentVotepointArticleVotepointAppealpointPurchaseInvitecodepointForward"

var _DataTypeNames = []string{
	_DataTypeName[0:7],
	_DataTypeName[7:14],
	_DataTypeName[14:16],
	_DataTypeName[16:25],
	_DataTypeName[25:38],
	_DataTypeName[38:49],
	_DataTypeName[49:62],
	_DataTypeName[62:80],
	_DataTypeName[80:97],
	_DataTypeName[97:114],
	_DataTypeName[114:133],
	_DataTypeName[133:158],
	_DataTypeName[158:177],
	_DataTypeName[177:195],
	_DataTypeName[195:209],
	_DataTypeName[209:222],
	_DataTypeName[222:235],
	_DataTypeName[235:251],
	_DataTypeName[251:268],
	_DataTypeName[268:282],
	_DataTypeName[282:297],
	_DataTypeName[297:308],
	_DataTypeName[308:329],
	_DataTypeName[329:352],
	_DataTypeName[352:368],
	_DataTypeName[368:384],
	_DataTypeName[384:395],
	_DataTypeName[395:418],
	_DataTypeName[418:430],
}

// DataTypeNames returns a list of possible string values of DataType.
func DataTypeNames() []string {
	tmp := make([]string, len(_DataTypeNames))
	copy(tmp, _DataTypeNames)
	return tmp
}

// DataTypeValues returns a list of the values for DataType
func DataTypeValues() []DataType {
	return []DataType{
		DataTypeArticle,
		DataTypeComment,
		DataTypeAt,
		DataTypeCommented,
		DataTypeFollowingUser,
		DataTypePointCharge,
		DataTypePointTransfer,
		DataTypePointArticleReward,
		DataTypePointArticleThank,
		DataTypePointCommentThank,
		DataTypePointInviteRegister,
		DataTypePointInviteJoinActivation,
		DataTypePointPerfectArticle,
		DataTypePointCommentAccept,
		DataTypePointFollowing,
		DataTypePointFollower,
		DataTypePointExchange,
		DataTypePointAbuseDeduct,
		DataTypePointStickArticle,
		DataTypePointRedPacket,
		DataTypePointTopArticle,
		DataTypePointReport,
		DataTypePointRepublishArticle,
		DataTypePointSellerBuyerAdvance,
		DataTypePointCommentVote,
		DataTypePointArticleVote,
		DataTypePointAppeal,
		DataTypePointPurchaseInvitecode,
		DataTypePointForward,
	}
}

var _DataTypeMap = map[DataType]string{
	DataTypeArticle:                   _DataTypeName[0:7],
	DataTypeComment:                   _DataTypeName[7:14],
	DataTypeAt:                        _DataTypeName[14:16],
	DataTypeCommented:                 _DataTypeName[16:25],
	DataTypeFollowingUser:             _DataTypeName[25:38],
	DataTypePointCharge:               _DataTypeName[38:49],
	DataTypePointTransfer:             _DataTypeName[49:62],
	DataTypePointArticleReward:        _DataTypeName[62:80],
	DataTypePointArticleThank:         _DataTypeName[80:97],
	DataTypePointCommentThank:         _DataTypeName[97:114],
	DataTypePointInviteRegister:       _DataTypeName[114:133],
	DataTypePointInviteJoinActivation: _DataTypeName[133:158],
	DataTypePointPerfectArticle:       _DataTypeName[158:177],
	DataTypePointCommentAccept:        _DataTypeName[177:195],
	DataTypePointFollowing:            _DataTypeName[195:209],
	DataTypePointFollower:             _DataTypeName[209:222],
	DataTypePointExchange:             _DataTypeName[222:235],
	DataTypePointAbuseDeduct:          _DataTypeName[235:251],
	DataTypePointStickArticle:         _DataTypeName[251:268],
	DataTypePointRedPacket:            _DataTypeName[268:282],
	DataTypePointTopArticle:           _DataTypeName[282:297],
	DataTypePointReport:               _DataTypeName[297:308],
	DataTypePointRepublishArticle:     _DataTypeName[308:329],
	DataTypePointSellerBuyerAdvance:   _DataTypeName[329:352],
	DataTypePointCommentVote:          _DataTypeName[352:368],
	DataTypePointArticleVote:          _DataTypeName[368:384],
	DataTypePointAppeal:               _DataTypeName[384:395],
	DataTypePointPurchaseInvitecode:   _DataTypeName[395:418],
	DataTypePointForward:              _DataTypeName[418:430],
}

// String implements the Stringer interface.
func (x DataType) String() string {
	if str, ok := _DataTypeMap[x]; ok {
		return str
	}
	return fmt.Sprintf("DataType(%d)", x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x DataType) IsValid() bool {
	_, ok := _DataTypeMap[x]
	return ok
}

var _DataTypeValue = map[string]DataType{
	_DataTypeName[0:7]:     DataTypeArticle,
	_DataTypeName[7:14]:    DataTypeComment,
	_DataTypeName[14:16]:   DataTypeAt,
	_DataTypeName[16:25]:   DataTypeCommented,
	_DataTypeName[25:38]:   DataTypeFollowingUser,
	_DataTypeName[38:49]:   DataTypePointCharge,
	_DataTypeName[49:62]:   DataTypePointTransfer,
	_DataTypeName[62:80]:   DataTypePointArticleReward,
	_DataTypeName[80:97]:   DataTypePointArticleThank,
	_DataTypeName[97:114]:  DataTypePointCommentThank,
	_DataTypeName[114:133]: DataTypePointInviteRegister,
	_DataTypeName[133:158]: DataTypePointInviteJoinActivation,
	_DataTypeName[158:177]: DataTypePointPerfectArticle,
	_DataTypeName[177:195]: DataTypePointCommentAccept,
	_DataTypeName[195:209]: DataTypePointFollowing,
	_DataTypeName[209:222]: DataTypePointFollower,
	_DataTypeName[222:235]: DataTypePointExchange,
	_DataTypeName[235:251]: DataTypePointAbuseDeduct,
	_DataTypeName[251:268]: DataTypePointStickArticle,
	_DataTypeName[268:282]: DataTypePointRedPacket,
	_DataTypeName[282:297]: DataTypePointTopArticle,
	_DataTypeName[297:308]: DataTypePointReport,
	_DataTypeName[308:329]: DataTypePointRepublishArticle,
	_DataTypeName[329:352]: DataTypePointSellerBuyerAdvance,
	_DataTypeName[352:368]: DataTypePointCommentVote,
	_DataTypeName[368:384]: DataTypePointArticleVote,
	_DataTypeName[384:395]: DataTypePointAppeal,
	_DataTypeName[395:418]: DataTypePointPurchaseInvitecode,
	_DataTypeName[418:430]: DataTypePointForward,
}

// ParseDataType attempts to convert a string to a DataType.
func ParseDataType(name string) (DataType, error) {
	if x, ok := _DataTypeValue[name]; ok {
		return x, nil
	}
	return DataType(0), fmt.Errorf("%s is %w", name, ErrInvalidDataType)
}

// MustParseDataType converts a string to a DataType, and panics if is not valid.
func MustParseDataType(name string) DataType {
	val, err := ParseDataType(name)
	if err != nil {
		panic(err)
	}
	return val
}

func (x DataType) Ptr() *DataType {
	return &x
}

// MarshalText implements the text marshaller method.
func (x DataType) MarshalText() ([]byte, error) {
	return []byte(x.String()), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *DataType) UnmarshalText(text []byte) error {
	name := string(text)
	tmp, err := ParseDataType(name)
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

const (
	// NotificationTypePoint is a NotificationType of type point.
	// 积分
	NotificationTypePoint NotificationType = "point"
	// NotificationTypeCommented is a NotificationType of type commented.
	// 收到的回帖
	NotificationTypeCommented NotificationType = "commented"
	// NotificationTypeReply is a NotificationType of type reply.
	// 收到的回复
	NotificationTypeReply NotificationType = "reply"
	// NotificationTypeAt is a NotificationType of type at.
	// 提及我的
	NotificationTypeAt NotificationType = "at"
	// NotificationTypeFollowing is a NotificationType of type following.
	// 我关注的
	NotificationTypeFollowing NotificationType = "following"
	// NotificationTypeBroadcast is a NotificationType of type broadcast.
	// 同城
	NotificationTypeBroadcast NotificationType = "broadcast"
	// NotificationTypeSysAnnounce is a NotificationType of type sys-announce.
	// 系统
	NotificationTypeSysAnnounce NotificationType = "sys-announce"
)

var ErrInvalidNotificationType = fmt.Errorf("not a valid NotificationType, try [%s]", strings.Join(_NotificationTypeNames, ", "))

var _NotificationTypeNames = []string{
	string(NotificationTypePoint),
	string(NotificationTypeCommented),
	string(NotificationTypeReply),
	string(NotificationTypeAt),
	string(NotificationTypeFollowing),
	string(NotificationTypeBroadcast),
	string(NotificationTypeSysAnnounce),
}

// NotificationTypeNames returns a list of possible string values of NotificationType.
func NotificationTypeNames() []string {
	tmp := make([]string, len(_NotificationTypeNames))
	copy(tmp, _NotificationTypeNames)
	return tmp
}

// NotificationTypeValues returns a list of the values for NotificationType
func NotificationTypeValues() []NotificationType {
	return []NotificationType{
		NotificationTypePoint,
		NotificationTypeCommented,
		NotificationTypeReply,
		NotificationTypeAt,
		NotificationTypeFollowing,
		NotificationTypeBroadcast,
		NotificationTypeSysAnnounce,
	}
}

// String implements the Stringer interface.
func (x NotificationType) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x NotificationType) IsValid() bool {
	_, err := ParseNotificationType(string(x))
	return err == nil
}

var _NotificationTypeValue = map[string]NotificationType{
	"point":        NotificationTypePoint,
	"commented":    NotificationTypeCommented,
	"reply":        NotificationTypeReply,
	"at":           NotificationTypeAt,
	"following":    NotificationTypeFollowing,
	"broadcast":    NotificationTypeBroadcast,
	"sys-announce": NotificationTypeSysAnnounce,
}

// ParseNotificationType attempts to convert a string to a NotificationType.
func ParseNotificationType(name string) (NotificationType, error) {
	if x, ok := _NotificationTypeValue[name]; ok {
		return x, nil
	}
	return NotificationType(""), fmt.Errorf("%s is %w", name, ErrInvalidNotificationType)
}

// MustParseNotificationType converts a string to a NotificationType, and panics if is not valid.
func MustParseNotificationType(name string) NotificationType {
	val, err := ParseNotificationType(name)
	if err != nil {
		panic(err)
	}
	return val
}

func (x NotificationType) Ptr() *NotificationType {
	return &x
}

// MarshalText implements the text marshaller method.
func (x NotificationType) MarshalText() ([]byte, error) {
	return []byte(string(x)), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *NotificationType) UnmarshalText(text []byte) error {
	tmp, err := ParseNotificationType(string(text))
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}
