// Code generated by go-enum DO NOT EDIT.
// Version:
// Revision:
// Build Date:
// Built By:

package types

import (
	"fmt"
	"strings"
)

const (
	// ItemTypeCheckin1day is a ItemType of type checkin1day.
	ItemTypeCheckin1day ItemType = "checkin1day"
	// ItemTypePatchCheckinCard is a ItemType of type patchCheckinCard.
	ItemTypePatchCheckinCard ItemType = "patchCheckinCard"
	// ItemTypePatchStart is a ItemType of type patchStart.
	ItemTypePatchStart ItemType = "patchStart"
	// ItemTypeSysCheckinRemain is a ItemType of type sysCheckinRemain.
	ItemTypeSysCheckinRemain ItemType = "sysCheckinRemain"
)

var ErrInvalidItemType = fmt.Errorf("not a valid ItemType, try [%s]", strings.Join(_ItemTypeNames, ", "))

var _ItemTypeNames = []string{
	string(ItemTypeCheckin1day),
	string(ItemTypePatchCheckinCard),
	string(ItemTypePatchStart),
	string(ItemTypeSysCheckinRemain),
}

// ItemTypeNames returns a list of possible string values of ItemType.
func ItemTypeNames() []string {
	tmp := make([]string, len(_ItemTypeNames))
	copy(tmp, _ItemTypeNames)
	return tmp
}

// ItemTypeValues returns a list of the values for ItemType
func ItemTypeValues() []ItemType {
	return []ItemType{
		ItemTypeCheckin1day,
		ItemTypePatchCheckinCard,
		ItemTypePatchStart,
		ItemTypeSysCheckinRemain,
	}
}

// String implements the Stringer interface.
func (x ItemType) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x ItemType) IsValid() bool {
	_, err := ParseItemType(string(x))
	return err == nil
}

var _ItemTypeValue = map[string]ItemType{
	"checkin1day":      ItemTypeCheckin1day,
	"patchCheckinCard": ItemTypePatchCheckinCard,
	"patchStart":       ItemTypePatchStart,
	"sysCheckinRemain": ItemTypeSysCheckinRemain,
}

// ParseItemType attempts to convert a string to a ItemType.
func ParseItemType(name string) (ItemType, error) {
	if x, ok := _ItemTypeValue[name]; ok {
		return x, nil
	}
	return ItemType(""), fmt.Errorf("%s is %w", name, ErrInvalidItemType)
}

// MustParseItemType converts a string to a ItemType, and panics if is not valid.
func MustParseItemType(name string) ItemType {
	val, err := ParseItemType(name)
	if err != nil {
		panic(err)
	}
	return val
}

func (x ItemType) Ptr() *ItemType {
	return &x
}

// MarshalText implements the text marshaller method.
func (x ItemType) MarshalText() ([]byte, error) {
	return []byte(string(x)), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *ItemType) UnmarshalText(text []byte) error {
	tmp, err := ParseItemType(string(text))
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}
