// Code generated by go-enum DO NOT EDIT.
// Version:
// Revision:
// Build Date:
// Built By:

package types

import (
	"fmt"
	"strings"
)

const (
	// DataTypeArticle is a DataType of type Article.
	// 文章
	DataTypeArticle DataType = iota
	// DataTypeComment is a DataType of type Comment.
	// 评论
	DataTypeComment
	// DataTypeAt is a DataType of type At.
	// @
	DataTypeAt
	// DataTypeCommented is a DataType of type Commented.
	// 被评论
	DataTypeCommented
	// DataTypeFollowingUser is a DataType of type FollowingUser.
	// 关注用户
	DataTypeFollowingUser
	// DataTypePointCharge is a DataType of type PointCharge.
	// 积分 - 充值
	DataTypePointCharge
	// DataTypePointTransfer is a DataType of type PointTransfer.
	// 积分 - 转账
	DataTypePointTransfer
	// DataTypePointArticleReward is a DataType of type PointArticleReward.
	// 积分 - 文章打赏
	DataTypePointArticleReward
	// DataTypePointCommentThank is a DataType of type PointCommentThank.
	// 积分 - 评论感谢
	DataTypePointCommentThank
	// DataTypeBroadcast is a DataType of type Broadcast.
	// 同城广播
	DataTypeBroadcast
	// DataTypePointExchange is a DataType of type PointExchange.
	// 积分 - 交易
	DataTypePointExchange
	// DataTypeAbusePointDeduct is a DataType of type AbusePointDeduct.
	// 积分 - 违规扣除
	DataTypeAbusePointDeduct
	// DataTypePointArticleThank is a DataType of type PointArticleThank.
	// 积分 - 文章被感谢
	DataTypePointArticleThank
	// DataTypeReply is a DataType of type Reply.
	// 回复
	DataTypeReply
	// DataTypeInvitecodeUsed is a DataType of type InvitecodeUsed.
	// 使用邀请码
	DataTypeInvitecodeUsed
	// DataTypeSysAnnounceArticle is a DataType of type SysAnnounceArticle.
	// 系统公告 - 文章
	DataTypeSysAnnounceArticle
	// DataTypeSysAnnounceNewUser is a DataType of type SysAnnounceNewUser.
	// 系统公告 - 新用户
	DataTypeSysAnnounceNewUser
	// DataTypeNewFollower is a DataType of type NewFollower.
	// 新的关注者
	DataTypeNewFollower
	// DataTypeInvitationLinkUsed is a DataType of type InvitationLinkUsed.
	// 邀请链接
	DataTypeInvitationLinkUsed
	// DataTypeSysAnnounceRoleChanged is a DataType of type SysAnnounceRoleChanged.
	// 系统通知 - 角色变化
	DataTypeSysAnnounceRoleChanged
	// DataTypeFollowingArticleUpdate is a DataType of type FollowingArticleUpdate.
	// 关注的文章更新
	DataTypeFollowingArticleUpdate
	// DataTypeFollowingArticleComment is a DataType of type FollowingArticleComment.
	// 关注的文章评论
	DataTypeFollowingArticleComment
	// DataTypePointPerfectArticle is a DataType of type PointPerfectArticle.
	// 积分 - 文章优选
	DataTypePointPerfectArticle
	// DataTypeArticleNewFollower is a DataType of type ArticleNewFollower.
	// 文章新的被关注者
	DataTypeArticleNewFollower
	// DataTypeArticleNewWatcher is a DataType of type ArticleNewWatcher.
	// 文章新的关注者
	DataTypeArticleNewWatcher
	// DataTypeCommentVoteUp is a DataType of type CommentVoteUp.
	// 评论点赞
	DataTypeCommentVoteUp
	// DataTypeCommentVoteDown is a DataType of type CommentVoteDown.
	// 评论点踩
	DataTypeCommentVoteDown
	// DataTypeArticleVoteUp is a DataType of type ArticleVoteUp.
	// 文章被点赞
	DataTypeArticleVoteUp
	// DataTypeArticleVoteDown is a DataType of type ArticleVoteDown.
	// 文章被点踩
	DataTypeArticleVoteDown
	// DataTypePointCommentAccept is a DataType of type PointCommentAccept.
	// 积分 - 评论被接受
	DataTypePointCommentAccept DataType = iota + 4
	// DataTypePointReportHandled is a DataType of type PointReportHandled.
	// 积分 - 举报处理
	DataTypePointReportHandled DataType = iota + 6
	// DataTypeChatRoomAt is a DataType of type ChatRoomAt.
	// 聊天室 @
	DataTypeChatRoomAt DataType = iota + 7
	// DataTypeRedPacket is a DataType of type RedPacket.
	// 专属红包提醒
	DataTypeRedPacket
)

var ErrInvalidDataType = fmt.Errorf("not a valid DataType, try [%s]", strings.Join(_DataTypeNames, ", "))

const _DataTypeName = "articlecommentatcommentedfollowingUserpointChargepointTransferpointArticleRewardpointCommentThankbroadcastpointExchangeabusePointDeductpointArticleThankreplyinvitecodeUsedsysAnnounceArticlesysAnnounceNewUsernewFollowerinvitationLinkUsedsysAnnounceRoleChangedfollowingArticleUpdatefollowingArticleCommentpointPerfectArticlearticleNewFollowerarticleNewWatchercommentVoteUpcommentVoteDownarticleVoteUparticleVoteDownpointCommentAcceptpointReportHandledchatRoomAtredPacket"

var _DataTypeNames = []string{
	_DataTypeName[0:7],
	_DataTypeName[7:14],
	_DataTypeName[14:16],
	_DataTypeName[16:25],
	_DataTypeName[25:38],
	_DataTypeName[38:49],
	_DataTypeName[49:62],
	_DataTypeName[62:80],
	_DataTypeName[80:97],
	_DataTypeName[97:106],
	_DataTypeName[106:119],
	_DataTypeName[119:135],
	_DataTypeName[135:152],
	_DataTypeName[152:157],
	_DataTypeName[157:171],
	_DataTypeName[171:189],
	_DataTypeName[189:207],
	_DataTypeName[207:218],
	_DataTypeName[218:236],
	_DataTypeName[236:258],
	_DataTypeName[258:280],
	_DataTypeName[280:303],
	_DataTypeName[303:322],
	_DataTypeName[322:340],
	_DataTypeName[340:357],
	_DataTypeName[357:370],
	_DataTypeName[370:385],
	_DataTypeName[385:398],
	_DataTypeName[398:413],
	_DataTypeName[413:431],
	_DataTypeName[431:449],
	_DataTypeName[449:459],
	_DataTypeName[459:468],
}

// DataTypeNames returns a list of possible string values of DataType.
func DataTypeNames() []string {
	tmp := make([]string, len(_DataTypeNames))
	copy(tmp, _DataTypeNames)
	return tmp
}

// DataTypeValues returns a list of the values for DataType
func DataTypeValues() []DataType {
	return []DataType{
		DataTypeArticle,
		DataTypeComment,
		DataTypeAt,
		DataTypeCommented,
		DataTypeFollowingUser,
		DataTypePointCharge,
		DataTypePointTransfer,
		DataTypePointArticleReward,
		DataTypePointCommentThank,
		DataTypeBroadcast,
		DataTypePointExchange,
		DataTypeAbusePointDeduct,
		DataTypePointArticleThank,
		DataTypeReply,
		DataTypeInvitecodeUsed,
		DataTypeSysAnnounceArticle,
		DataTypeSysAnnounceNewUser,
		DataTypeNewFollower,
		DataTypeInvitationLinkUsed,
		DataTypeSysAnnounceRoleChanged,
		DataTypeFollowingArticleUpdate,
		DataTypeFollowingArticleComment,
		DataTypePointPerfectArticle,
		DataTypeArticleNewFollower,
		DataTypeArticleNewWatcher,
		DataTypeCommentVoteUp,
		DataTypeCommentVoteDown,
		DataTypeArticleVoteUp,
		DataTypeArticleVoteDown,
		DataTypePointCommentAccept,
		DataTypePointReportHandled,
		DataTypeChatRoomAt,
		DataTypeRedPacket,
	}
}

var _DataTypeMap = map[DataType]string{
	DataTypeArticle:                 _DataTypeName[0:7],
	DataTypeComment:                 _DataTypeName[7:14],
	DataTypeAt:                      _DataTypeName[14:16],
	DataTypeCommented:               _DataTypeName[16:25],
	DataTypeFollowingUser:           _DataTypeName[25:38],
	DataTypePointCharge:             _DataTypeName[38:49],
	DataTypePointTransfer:           _DataTypeName[49:62],
	DataTypePointArticleReward:      _DataTypeName[62:80],
	DataTypePointCommentThank:       _DataTypeName[80:97],
	DataTypeBroadcast:               _DataTypeName[97:106],
	DataTypePointExchange:           _DataTypeName[106:119],
	DataTypeAbusePointDeduct:        _DataTypeName[119:135],
	DataTypePointArticleThank:       _DataTypeName[135:152],
	DataTypeReply:                   _DataTypeName[152:157],
	DataTypeInvitecodeUsed:          _DataTypeName[157:171],
	DataTypeSysAnnounceArticle:      _DataTypeName[171:189],
	DataTypeSysAnnounceNewUser:      _DataTypeName[189:207],
	DataTypeNewFollower:             _DataTypeName[207:218],
	DataTypeInvitationLinkUsed:      _DataTypeName[218:236],
	DataTypeSysAnnounceRoleChanged:  _DataTypeName[236:258],
	DataTypeFollowingArticleUpdate:  _DataTypeName[258:280],
	DataTypeFollowingArticleComment: _DataTypeName[280:303],
	DataTypePointPerfectArticle:     _DataTypeName[303:322],
	DataTypeArticleNewFollower:      _DataTypeName[322:340],
	DataTypeArticleNewWatcher:       _DataTypeName[340:357],
	DataTypeCommentVoteUp:           _DataTypeName[357:370],
	DataTypeCommentVoteDown:         _DataTypeName[370:385],
	DataTypeArticleVoteUp:           _DataTypeName[385:398],
	DataTypeArticleVoteDown:         _DataTypeName[398:413],
	DataTypePointCommentAccept:      _DataTypeName[413:431],
	DataTypePointReportHandled:      _DataTypeName[431:449],
	DataTypeChatRoomAt:              _DataTypeName[449:459],
	DataTypeRedPacket:               _DataTypeName[459:468],
}

// String implements the Stringer interface.
func (x DataType) String() string {
	if str, ok := _DataTypeMap[x]; ok {
		return str
	}
	return fmt.Sprintf("DataType(%d)", x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x DataType) IsValid() bool {
	_, ok := _DataTypeMap[x]
	return ok
}

var _DataTypeValue = map[string]DataType{
	_DataTypeName[0:7]:     DataTypeArticle,
	_DataTypeName[7:14]:    DataTypeComment,
	_DataTypeName[14:16]:   DataTypeAt,
	_DataTypeName[16:25]:   DataTypeCommented,
	_DataTypeName[25:38]:   DataTypeFollowingUser,
	_DataTypeName[38:49]:   DataTypePointCharge,
	_DataTypeName[49:62]:   DataTypePointTransfer,
	_DataTypeName[62:80]:   DataTypePointArticleReward,
	_DataTypeName[80:97]:   DataTypePointCommentThank,
	_DataTypeName[97:106]:  DataTypeBroadcast,
	_DataTypeName[106:119]: DataTypePointExchange,
	_DataTypeName[119:135]: DataTypeAbusePointDeduct,
	_DataTypeName[135:152]: DataTypePointArticleThank,
	_DataTypeName[152:157]: DataTypeReply,
	_DataTypeName[157:171]: DataTypeInvitecodeUsed,
	_DataTypeName[171:189]: DataTypeSysAnnounceArticle,
	_DataTypeName[189:207]: DataTypeSysAnnounceNewUser,
	_DataTypeName[207:218]: DataTypeNewFollower,
	_DataTypeName[218:236]: DataTypeInvitationLinkUsed,
	_DataTypeName[236:258]: DataTypeSysAnnounceRoleChanged,
	_DataTypeName[258:280]: DataTypeFollowingArticleUpdate,
	_DataTypeName[280:303]: DataTypeFollowingArticleComment,
	_DataTypeName[303:322]: DataTypePointPerfectArticle,
	_DataTypeName[322:340]: DataTypeArticleNewFollower,
	_DataTypeName[340:357]: DataTypeArticleNewWatcher,
	_DataTypeName[357:370]: DataTypeCommentVoteUp,
	_DataTypeName[370:385]: DataTypeCommentVoteDown,
	_DataTypeName[385:398]: DataTypeArticleVoteUp,
	_DataTypeName[398:413]: DataTypeArticleVoteDown,
	_DataTypeName[413:431]: DataTypePointCommentAccept,
	_DataTypeName[431:449]: DataTypePointReportHandled,
	_DataTypeName[449:459]: DataTypeChatRoomAt,
	_DataTypeName[459:468]: DataTypeRedPacket,
}

// ParseDataType attempts to convert a string to a DataType.
func ParseDataType(name string) (DataType, error) {
	if x, ok := _DataTypeValue[name]; ok {
		return x, nil
	}
	return DataType(0), fmt.Errorf("%s is %w", name, ErrInvalidDataType)
}

// MustParseDataType converts a string to a DataType, and panics if is not valid.
func MustParseDataType(name string) DataType {
	val, err := ParseDataType(name)
	if err != nil {
		panic(err)
	}
	return val
}

func (x DataType) Ptr() *DataType {
	return &x
}

const (
	// NotificationTypePoint is a NotificationType of type point.
	// 积分
	NotificationTypePoint NotificationType = "point"
	// NotificationTypeCommented is a NotificationType of type commented.
	// 收到的回帖
	NotificationTypeCommented NotificationType = "commented"
	// NotificationTypeReply is a NotificationType of type reply.
	// 收到的回复
	NotificationTypeReply NotificationType = "reply"
	// NotificationTypeAt is a NotificationType of type at.
	// 提及我的
	NotificationTypeAt NotificationType = "at"
	// NotificationTypeFollowing is a NotificationType of type following.
	// 我关注的
	NotificationTypeFollowing NotificationType = "following"
	// NotificationTypeBroadcast is a NotificationType of type broadcast.
	// 同城
	NotificationTypeBroadcast NotificationType = "broadcast"
	// NotificationTypeSysAnnounce is a NotificationType of type sys-announce.
	// 系统
	NotificationTypeSysAnnounce NotificationType = "sys-announce"
)

var ErrInvalidNotificationType = fmt.Errorf("not a valid NotificationType, try [%s]", strings.Join(_NotificationTypeNames, ", "))

var _NotificationTypeNames = []string{
	string(NotificationTypePoint),
	string(NotificationTypeCommented),
	string(NotificationTypeReply),
	string(NotificationTypeAt),
	string(NotificationTypeFollowing),
	string(NotificationTypeBroadcast),
	string(NotificationTypeSysAnnounce),
}

// NotificationTypeNames returns a list of possible string values of NotificationType.
func NotificationTypeNames() []string {
	tmp := make([]string, len(_NotificationTypeNames))
	copy(tmp, _NotificationTypeNames)
	return tmp
}

// NotificationTypeValues returns a list of the values for NotificationType
func NotificationTypeValues() []NotificationType {
	return []NotificationType{
		NotificationTypePoint,
		NotificationTypeCommented,
		NotificationTypeReply,
		NotificationTypeAt,
		NotificationTypeFollowing,
		NotificationTypeBroadcast,
		NotificationTypeSysAnnounce,
	}
}

// String implements the Stringer interface.
func (x NotificationType) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x NotificationType) IsValid() bool {
	_, err := ParseNotificationType(string(x))
	return err == nil
}

var _NotificationTypeValue = map[string]NotificationType{
	"point":        NotificationTypePoint,
	"commented":    NotificationTypeCommented,
	"reply":        NotificationTypeReply,
	"at":           NotificationTypeAt,
	"following":    NotificationTypeFollowing,
	"broadcast":    NotificationTypeBroadcast,
	"sys-announce": NotificationTypeSysAnnounce,
}

// ParseNotificationType attempts to convert a string to a NotificationType.
func ParseNotificationType(name string) (NotificationType, error) {
	if x, ok := _NotificationTypeValue[name]; ok {
		return x, nil
	}
	return NotificationType(""), fmt.Errorf("%s is %w", name, ErrInvalidNotificationType)
}

// MustParseNotificationType converts a string to a NotificationType, and panics if is not valid.
func MustParseNotificationType(name string) NotificationType {
	val, err := ParseNotificationType(name)
	if err != nil {
		panic(err)
	}
	return val
}

func (x NotificationType) Ptr() *NotificationType {
	return &x
}
