// Code generated by go-enum DO NOT EDIT.
// Version:
// Revision:
// Build Date:
// Built By:

package types

import (
	"fmt"
	"strings"
)

const (
	// UserAppRoleHack is a UserAppRole of type Hack.
	// 黑客
	UserAppRoleHack UserAppRole = iota
	// UserAppRolePainter is a UserAppRole of type Painter.
	// 画家
	UserAppRolePainter
)

var ErrInvalidUserAppRole = fmt.Errorf("not a valid UserAppRole, try [%s]", strings.Join(_UserAppRoleNames, ", "))

const _UserAppRoleName = "hackpainter"

var _UserAppRoleNames = []string{
	_UserAppRoleName[0:4],
	_UserAppRoleName[4:11],
}

// UserAppRoleNames returns a list of possible string values of UserAppRole.
func UserAppRoleNames() []string {
	tmp := make([]string, len(_UserAppRoleNames))
	copy(tmp, _UserAppRoleNames)
	return tmp
}

// UserAppRoleValues returns a list of the values for UserAppRole
func UserAppRoleValues() []UserAppRole {
	return []UserAppRole{
		UserAppRoleHack,
		UserAppRolePainter,
	}
}

var _UserAppRoleMap = map[UserAppRole]string{
	UserAppRoleHack:    _UserAppRoleName[0:4],
	UserAppRolePainter: _UserAppRoleName[4:11],
}

// String implements the Stringer interface.
func (x UserAppRole) String() string {
	if str, ok := _UserAppRoleMap[x]; ok {
		return str
	}
	return fmt.Sprintf("UserAppRole(%d)", x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x UserAppRole) IsValid() bool {
	_, ok := _UserAppRoleMap[x]
	return ok
}

var _UserAppRoleValue = map[string]UserAppRole{
	_UserAppRoleName[0:4]:  UserAppRoleHack,
	_UserAppRoleName[4:11]: UserAppRolePainter,
}

// ParseUserAppRole attempts to convert a string to a UserAppRole.
func ParseUserAppRole(name string) (UserAppRole, error) {
	if x, ok := _UserAppRoleValue[name]; ok {
		return x, nil
	}
	return UserAppRole(0), fmt.Errorf("%s is %w", name, ErrInvalidUserAppRole)
}

// MustParseUserAppRole converts a string to a UserAppRole, and panics if is not valid.
func MustParseUserAppRole(name string) UserAppRole {
	val, err := ParseUserAppRole(name)
	if err != nil {
		panic(err)
	}
	return val
}

func (x UserAppRole) Ptr() *UserAppRole {
	return &x
}

// MarshalText implements the text marshaller method.
func (x UserAppRole) MarshalText() ([]byte, error) {
	return []byte(x.String()), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *UserAppRole) UnmarshalText(text []byte) error {
	name := string(text)
	tmp, err := ParseUserAppRole(name)
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}
