// Code generated by go-enum DO NOT EDIT.
// Version:
// Revision:
// Build Date:
// Built By:

package types

import (
	"fmt"
	"strings"
)

const (
	// VoteTypeUnvoted is a VoteType of type Unvoted.
	// 未投票
	VoteTypeUnvoted VoteType = iota + -1
	// VoteTypeUp is a VoteType of type Up.
	// 点赞
	VoteTypeUp
	// VoteTypeDown is a VoteType of type Down.
	// 点踩
	VoteTypeDown
)

var ErrInvalidVoteType = fmt.Errorf("not a valid VoteType, try [%s]", strings.Join(_VoteTypeNames, ", "))

const _VoteTypeName = "unvotedupdown"

var _VoteTypeNames = []string{
	_VoteTypeName[0:7],
	_VoteTypeName[7:9],
	_VoteTypeName[9:13],
}

// VoteTypeNames returns a list of possible string values of VoteType.
func VoteTypeNames() []string {
	tmp := make([]string, len(_VoteTypeNames))
	copy(tmp, _VoteTypeNames)
	return tmp
}

// VoteTypeValues returns a list of the values for VoteType
func VoteTypeValues() []VoteType {
	return []VoteType{
		VoteTypeUnvoted,
		VoteTypeUp,
		VoteTypeDown,
	}
}

var _VoteTypeMap = map[VoteType]string{
	VoteTypeUnvoted: _VoteTypeName[0:7],
	VoteTypeUp:      _VoteTypeName[7:9],
	VoteTypeDown:    _VoteTypeName[9:13],
}

// String implements the Stringer interface.
func (x VoteType) String() string {
	if str, ok := _VoteTypeMap[x]; ok {
		return str
	}
	return fmt.Sprintf("VoteType(%d)", x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x VoteType) IsValid() bool {
	_, ok := _VoteTypeMap[x]
	return ok
}

var _VoteTypeValue = map[string]VoteType{
	_VoteTypeName[0:7]:  VoteTypeUnvoted,
	_VoteTypeName[7:9]:  VoteTypeUp,
	_VoteTypeName[9:13]: VoteTypeDown,
}

// ParseVoteType attempts to convert a string to a VoteType.
func ParseVoteType(name string) (VoteType, error) {
	if x, ok := _VoteTypeValue[name]; ok {
		return x, nil
	}
	return VoteType(0), fmt.Errorf("%s is %w", name, ErrInvalidVoteType)
}

// MustParseVoteType converts a string to a VoteType, and panics if is not valid.
func MustParseVoteType(name string) VoteType {
	val, err := ParseVoteType(name)
	if err != nil {
		panic(err)
	}
	return val
}

func (x VoteType) Ptr() *VoteType {
	return &x
}

// MarshalText implements the text marshaller method.
func (x VoteType) MarshalText() ([]byte, error) {
	return []byte(x.String()), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *VoteType) UnmarshalText(text []byte) error {
	name := string(text)
	tmp, err := ParseVoteType(name)
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}
