// Code generated by go-enum DO NOT EDIT.
// Version:
// Revision:
// Build Date:
// Built By:

package types

import (
	"fmt"
	"strings"
)

const (
	// ReactionEmojiValueThumbsup is a ReactionEmojiValue of type thumbsup.
	// 👍 赞
	ReactionEmojiValueThumbsup ReactionEmojiValue = "thumbsup"
	// ReactionEmojiValuePlus is a ReactionEmojiValue of type plus.
	// ➕1️⃣ +1/同意/我也是
	ReactionEmojiValuePlus ReactionEmojiValue = "plus"
	// ReactionEmojiValueThumbsdown is a ReactionEmojiValue of type thumbsdown.
	// 👎	反对 / 不喜欢
	ReactionEmojiValueThumbsdown ReactionEmojiValue = "thumbsdown"
	// ReactionEmojiValueCheck is a ReactionEmojiValue of type check.
	// ✅	对 / 正确 / 通过
	ReactionEmojiValueCheck ReactionEmojiValue = "check"
	// ReactionEmojiValueCross is a ReactionEmojiValue of type cross.
	// ❌	错 / 否 / 不通过
	ReactionEmojiValueCross ReactionEmojiValue = "cross"
	// ReactionEmojiValueStar is a ReactionEmojiValue of type star.
	// ⭐	收藏 / 亮眼 / 很棒
	ReactionEmojiValueStar ReactionEmojiValue = "star"
	// ReactionEmojiValueHeart is a ReactionEmojiValue of type heart.
	// ❤️️	喜欢 / 支持
	ReactionEmojiValueHeart ReactionEmojiValue = "heart"
	// ReactionEmojiValueFire is a ReactionEmojiValue of type fire.
	// 🔥	热门 / 很强
	ReactionEmojiValueFire ReactionEmojiValue = "fire"
	// ReactionEmojiValueParty is a ReactionEmojiValue of type party.
	// 🎉	庆祝
	ReactionEmojiValueParty ReactionEmojiValue = "party"
	// ReactionEmojiValueLaugh is a ReactionEmojiValue of type laugh.
	// 😂	好笑
	ReactionEmojiValueLaugh ReactionEmojiValue = "laugh"
	// ReactionEmojiValueWow is a ReactionEmojiValue of type wow.
	// 😮	惊讶
	ReactionEmojiValueWow ReactionEmojiValue = "wow"
	// ReactionEmojiValueClap is a ReactionEmojiValue of type clap.
	// 👏	鼓掌 / 认可
	ReactionEmojiValueClap ReactionEmojiValue = "clap"
	// ReactionEmojiValueHundred is a ReactionEmojiValue of type hundred.
	// 💯	满分 / 非常认可
	ReactionEmojiValueHundred ReactionEmojiValue = "hundred"
	// ReactionEmojiValueRocket is a ReactionEmojiValue of type rocket.
	// 🚀	起飞 / 冲
	ReactionEmojiValueRocket ReactionEmojiValue = "rocket"
	// ReactionEmojiValueSalute is a ReactionEmojiValue of type salute.
	// 🖖	致意 / 打招呼
	ReactionEmojiValueSalute ReactionEmojiValue = "salute"
	// ReactionEmojiValueHandshake is a ReactionEmojiValue of type handshake.
	// 🤝	握手 / 达成一致
	ReactionEmojiValueHandshake ReactionEmojiValue = "handshake"
	// ReactionEmojiValueRaisedhands is a ReactionEmojiValue of type raisedhands.
	// 🙌	赞成 / 欢呼
	ReactionEmojiValueRaisedhands ReactionEmojiValue = "raisedhands"
	// ReactionEmojiValueMindblown is a ReactionEmojiValue of type mindblown.
	// 🤯	震惊 / 太强了
	ReactionEmojiValueMindblown ReactionEmojiValue = "mindblown"
	// ReactionEmojiValueThinking is a ReactionEmojiValue of type thinking.
	// 🤔	思考 / 存疑
	ReactionEmojiValueThinking ReactionEmojiValue = "thinking"
	// ReactionEmojiValueEyes is a ReactionEmojiValue of type eyes.
	// 👀	围观 / 关注
	ReactionEmojiValueEyes ReactionEmojiValue = "eyes"
	// ReactionEmojiValueCry is a ReactionEmojiValue of type cry.
	// 😢	难过 / 共情
	ReactionEmojiValueCry ReactionEmojiValue = "cry"
	// ReactionEmojiValueAngry is a ReactionEmojiValue of type angry.
	// 😡	生气 / 不满
	ReactionEmojiValueAngry ReactionEmojiValue = "angry"
	// ReactionEmojiValuePray is a ReactionEmojiValue of type pray.
	// 🙏	祈祷 / 拜托 / 感谢
	ReactionEmojiValuePray ReactionEmojiValue = "pray"
	// ReactionEmojiValueBrokenheart is a ReactionEmojiValue of type brokenheart.
	// 💔	破防 / 难受
	ReactionEmojiValueBrokenheart ReactionEmojiValue = "brokenheart"
	// ReactionEmojiValueHeartonfire is a ReactionEmojiValue of type heartonfire.
	// ❤️️🔥	上头 / 强烈喜欢
	ReactionEmojiValueHeartonfire ReactionEmojiValue = "heartonfire"
	// ReactionEmojiValueSkull is a ReactionEmojiValue of type skull.
	// 💀	笑死 / 绝了
	ReactionEmojiValueSkull ReactionEmojiValue = "skull"
	// ReactionEmojiValueClown is a ReactionEmojiValue of type clown.
	// 🤡	小丑 / 离谱
	ReactionEmojiValueClown ReactionEmojiValue = "clown"
	// ReactionEmojiValuePoop is a ReactionEmojiValue of type poop.
	// 💩	拉胯 / 吐槽
	ReactionEmojiValuePoop ReactionEmojiValue = "poop"
)

var ErrInvalidReactionEmojiValue = fmt.Errorf("not a valid ReactionEmojiValue, try [%s]", strings.Join(_ReactionEmojiValueNames, ", "))

var _ReactionEmojiValueNames = []string{
	string(ReactionEmojiValueThumbsup),
	string(ReactionEmojiValuePlus),
	string(ReactionEmojiValueThumbsdown),
	string(ReactionEmojiValueCheck),
	string(ReactionEmojiValueCross),
	string(ReactionEmojiValueStar),
	string(ReactionEmojiValueHeart),
	string(ReactionEmojiValueFire),
	string(ReactionEmojiValueParty),
	string(ReactionEmojiValueLaugh),
	string(ReactionEmojiValueWow),
	string(ReactionEmojiValueClap),
	string(ReactionEmojiValueHundred),
	string(ReactionEmojiValueRocket),
	string(ReactionEmojiValueSalute),
	string(ReactionEmojiValueHandshake),
	string(ReactionEmojiValueRaisedhands),
	string(ReactionEmojiValueMindblown),
	string(ReactionEmojiValueThinking),
	string(ReactionEmojiValueEyes),
	string(ReactionEmojiValueCry),
	string(ReactionEmojiValueAngry),
	string(ReactionEmojiValuePray),
	string(ReactionEmojiValueBrokenheart),
	string(ReactionEmojiValueHeartonfire),
	string(ReactionEmojiValueSkull),
	string(ReactionEmojiValueClown),
	string(ReactionEmojiValuePoop),
}

// ReactionEmojiValueNames returns a list of possible string values of ReactionEmojiValue.
func ReactionEmojiValueNames() []string {
	tmp := make([]string, len(_ReactionEmojiValueNames))
	copy(tmp, _ReactionEmojiValueNames)
	return tmp
}

// ReactionEmojiValueValues returns a list of the values for ReactionEmojiValue
func ReactionEmojiValueValues() []ReactionEmojiValue {
	return []ReactionEmojiValue{
		ReactionEmojiValueThumbsup,
		ReactionEmojiValuePlus,
		ReactionEmojiValueThumbsdown,
		ReactionEmojiValueCheck,
		ReactionEmojiValueCross,
		ReactionEmojiValueStar,
		ReactionEmojiValueHeart,
		ReactionEmojiValueFire,
		ReactionEmojiValueParty,
		ReactionEmojiValueLaugh,
		ReactionEmojiValueWow,
		ReactionEmojiValueClap,
		ReactionEmojiValueHundred,
		ReactionEmojiValueRocket,
		ReactionEmojiValueSalute,
		ReactionEmojiValueHandshake,
		ReactionEmojiValueRaisedhands,
		ReactionEmojiValueMindblown,
		ReactionEmojiValueThinking,
		ReactionEmojiValueEyes,
		ReactionEmojiValueCry,
		ReactionEmojiValueAngry,
		ReactionEmojiValuePray,
		ReactionEmojiValueBrokenheart,
		ReactionEmojiValueHeartonfire,
		ReactionEmojiValueSkull,
		ReactionEmojiValueClown,
		ReactionEmojiValuePoop,
	}
}

// String implements the Stringer interface.
func (x ReactionEmojiValue) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x ReactionEmojiValue) IsValid() bool {
	_, err := ParseReactionEmojiValue(string(x))
	return err == nil
}

var _ReactionEmojiValueValue = map[string]ReactionEmojiValue{
	"thumbsup":    ReactionEmojiValueThumbsup,
	"plus":        ReactionEmojiValuePlus,
	"thumbsdown":  ReactionEmojiValueThumbsdown,
	"check":       ReactionEmojiValueCheck,
	"cross":       ReactionEmojiValueCross,
	"star":        ReactionEmojiValueStar,
	"heart":       ReactionEmojiValueHeart,
	"fire":        ReactionEmojiValueFire,
	"party":       ReactionEmojiValueParty,
	"laugh":       ReactionEmojiValueLaugh,
	"wow":         ReactionEmojiValueWow,
	"clap":        ReactionEmojiValueClap,
	"hundred":     ReactionEmojiValueHundred,
	"rocket":      ReactionEmojiValueRocket,
	"salute":      ReactionEmojiValueSalute,
	"handshake":   ReactionEmojiValueHandshake,
	"raisedhands": ReactionEmojiValueRaisedhands,
	"mindblown":   ReactionEmojiValueMindblown,
	"thinking":    ReactionEmojiValueThinking,
	"eyes":        ReactionEmojiValueEyes,
	"cry":         ReactionEmojiValueCry,
	"angry":       ReactionEmojiValueAngry,
	"pray":        ReactionEmojiValuePray,
	"brokenheart": ReactionEmojiValueBrokenheart,
	"heartonfire": ReactionEmojiValueHeartonfire,
	"skull":       ReactionEmojiValueSkull,
	"clown":       ReactionEmojiValueClown,
	"poop":        ReactionEmojiValuePoop,
}

// ParseReactionEmojiValue attempts to convert a string to a ReactionEmojiValue.
func ParseReactionEmojiValue(name string) (ReactionEmojiValue, error) {
	if x, ok := _ReactionEmojiValueValue[name]; ok {
		return x, nil
	}
	return ReactionEmojiValue(""), fmt.Errorf("%s is %w", name, ErrInvalidReactionEmojiValue)
}

// MustParseReactionEmojiValue converts a string to a ReactionEmojiValue, and panics if is not valid.
func MustParseReactionEmojiValue(name string) ReactionEmojiValue {
	val, err := ParseReactionEmojiValue(name)
	if err != nil {
		panic(err)
	}
	return val
}

func (x ReactionEmojiValue) Ptr() *ReactionEmojiValue {
	return &x
}

const (
	// ReactionGroupTypeEmoji is a ReactionGroupType of type emoji.
	// 表情
	ReactionGroupTypeEmoji ReactionGroupType = "emoji"
)

var ErrInvalidReactionGroupType = fmt.Errorf("not a valid ReactionGroupType, try [%s]", strings.Join(_ReactionGroupTypeNames, ", "))

var _ReactionGroupTypeNames = []string{
	string(ReactionGroupTypeEmoji),
}

// ReactionGroupTypeNames returns a list of possible string values of ReactionGroupType.
func ReactionGroupTypeNames() []string {
	tmp := make([]string, len(_ReactionGroupTypeNames))
	copy(tmp, _ReactionGroupTypeNames)
	return tmp
}

// ReactionGroupTypeValues returns a list of the values for ReactionGroupType
func ReactionGroupTypeValues() []ReactionGroupType {
	return []ReactionGroupType{
		ReactionGroupTypeEmoji,
	}
}

// String implements the Stringer interface.
func (x ReactionGroupType) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x ReactionGroupType) IsValid() bool {
	_, err := ParseReactionGroupType(string(x))
	return err == nil
}

var _ReactionGroupTypeValue = map[string]ReactionGroupType{
	"emoji": ReactionGroupTypeEmoji,
}

// ParseReactionGroupType attempts to convert a string to a ReactionGroupType.
func ParseReactionGroupType(name string) (ReactionGroupType, error) {
	if x, ok := _ReactionGroupTypeValue[name]; ok {
		return x, nil
	}
	return ReactionGroupType(""), fmt.Errorf("%s is %w", name, ErrInvalidReactionGroupType)
}

// MustParseReactionGroupType converts a string to a ReactionGroupType, and panics if is not valid.
func MustParseReactionGroupType(name string) ReactionGroupType {
	val, err := ParseReactionGroupType(name)
	if err != nil {
		panic(err)
	}
	return val
}

func (x ReactionGroupType) Ptr() *ReactionGroupType {
	return &x
}

const (
	// ReactionTargetTypeArticle is a ReactionTargetType of type article.
	// 文章
	ReactionTargetTypeArticle ReactionTargetType = "article"
	// ReactionTargetTypeComment is a ReactionTargetType of type comment.
	// 评论
	ReactionTargetTypeComment ReactionTargetType = "comment"
	// ReactionTargetTypeChat is a ReactionTargetType of type chat.
	// 聊天室消息
	ReactionTargetTypeChat ReactionTargetType = "chat"
)

var ErrInvalidReactionTargetType = fmt.Errorf("not a valid ReactionTargetType, try [%s]", strings.Join(_ReactionTargetTypeNames, ", "))

var _ReactionTargetTypeNames = []string{
	string(ReactionTargetTypeArticle),
	string(ReactionTargetTypeComment),
	string(ReactionTargetTypeChat),
}

// ReactionTargetTypeNames returns a list of possible string values of ReactionTargetType.
func ReactionTargetTypeNames() []string {
	tmp := make([]string, len(_ReactionTargetTypeNames))
	copy(tmp, _ReactionTargetTypeNames)
	return tmp
}

// ReactionTargetTypeValues returns a list of the values for ReactionTargetType
func ReactionTargetTypeValues() []ReactionTargetType {
	return []ReactionTargetType{
		ReactionTargetTypeArticle,
		ReactionTargetTypeComment,
		ReactionTargetTypeChat,
	}
}

// String implements the Stringer interface.
func (x ReactionTargetType) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x ReactionTargetType) IsValid() bool {
	_, err := ParseReactionTargetType(string(x))
	return err == nil
}

var _ReactionTargetTypeValue = map[string]ReactionTargetType{
	"article": ReactionTargetTypeArticle,
	"comment": ReactionTargetTypeComment,
	"chat":    ReactionTargetTypeChat,
}

// ParseReactionTargetType attempts to convert a string to a ReactionTargetType.
func ParseReactionTargetType(name string) (ReactionTargetType, error) {
	if x, ok := _ReactionTargetTypeValue[name]; ok {
		return x, nil
	}
	return ReactionTargetType(""), fmt.Errorf("%s is %w", name, ErrInvalidReactionTargetType)
}

// MustParseReactionTargetType converts a string to a ReactionTargetType, and panics if is not valid.
func MustParseReactionTargetType(name string) ReactionTargetType {
	val, err := ParseReactionTargetType(name)
	if err != nil {
		panic(err)
	}
	return val
}

func (x ReactionTargetType) Ptr() *ReactionTargetType {
	return &x
}
