// Code generated by go-enum DO NOT EDIT.
// Version:
// Revision:
// Build Date:
// Built By:

package types

import (
	"fmt"
	"strings"
)

const (
	// EmojiGroupTypeCustom is a EmojiGroupType of type Custom.
	// 通用表情表分组
	EmojiGroupTypeCustom EmojiGroupType = iota
	// EmojiGroupTypeAll is a EmojiGroupType of type All.
	// 默认全部表情表分组
	EmojiGroupTypeAll
)

var ErrInvalidEmojiGroupType = fmt.Errorf("not a valid EmojiGroupType, try [%s]", strings.Join(_EmojiGroupTypeNames, ", "))

const _EmojiGroupTypeName = "customall"

var _EmojiGroupTypeNames = []string{
	_EmojiGroupTypeName[0:6],
	_EmojiGroupTypeName[6:9],
}

// EmojiGroupTypeNames returns a list of possible string values of EmojiGroupType.
func EmojiGroupTypeNames() []string {
	tmp := make([]string, len(_EmojiGroupTypeNames))
	copy(tmp, _EmojiGroupTypeNames)
	return tmp
}

// EmojiGroupTypeValues returns a list of the values for EmojiGroupType
func EmojiGroupTypeValues() []EmojiGroupType {
	return []EmojiGroupType{
		EmojiGroupTypeCustom,
		EmojiGroupTypeAll,
	}
}

var _EmojiGroupTypeMap = map[EmojiGroupType]string{
	EmojiGroupTypeCustom: _EmojiGroupTypeName[0:6],
	EmojiGroupTypeAll:    _EmojiGroupTypeName[6:9],
}

// String implements the Stringer interface.
func (x EmojiGroupType) String() string {
	if str, ok := _EmojiGroupTypeMap[x]; ok {
		return str
	}
	return fmt.Sprintf("EmojiGroupType(%d)", x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x EmojiGroupType) IsValid() bool {
	_, ok := _EmojiGroupTypeMap[x]
	return ok
}

var _EmojiGroupTypeValue = map[string]EmojiGroupType{
	_EmojiGroupTypeName[0:6]: EmojiGroupTypeCustom,
	_EmojiGroupTypeName[6:9]: EmojiGroupTypeAll,
}

// ParseEmojiGroupType attempts to convert a string to a EmojiGroupType.
func ParseEmojiGroupType(name string) (EmojiGroupType, error) {
	if x, ok := _EmojiGroupTypeValue[name]; ok {
		return x, nil
	}
	return EmojiGroupType(0), fmt.Errorf("%s is %w", name, ErrInvalidEmojiGroupType)
}

// MustParseEmojiGroupType converts a string to a EmojiGroupType, and panics if is not valid.
func MustParseEmojiGroupType(name string) EmojiGroupType {
	val, err := ParseEmojiGroupType(name)
	if err != nil {
		panic(err)
	}
	return val
}

func (x EmojiGroupType) Ptr() *EmojiGroupType {
	return &x
}
