// Code generated by go-enum DO NOT EDIT.
// Version:
// Revision:
// Build Date:
// Built By:

package types

import (
	"fmt"
	"strings"
)

const (
	// MedalReorderDirectionUp is a MedalReorderDirection of type up.
	// 上移
	MedalReorderDirectionUp MedalReorderDirection = "up"
	// MedalReorderDirectionDown is a MedalReorderDirection of type down.
	// 下移
	MedalReorderDirectionDown MedalReorderDirection = "down"
)

var ErrInvalidMedalReorderDirection = fmt.Errorf("not a valid MedalReorderDirection, try [%s]", strings.Join(_MedalReorderDirectionNames, ", "))

var _MedalReorderDirectionNames = []string{
	string(MedalReorderDirectionUp),
	string(MedalReorderDirectionDown),
}

// MedalReorderDirectionNames returns a list of possible string values of MedalReorderDirection.
func MedalReorderDirectionNames() []string {
	tmp := make([]string, len(_MedalReorderDirectionNames))
	copy(tmp, _MedalReorderDirectionNames)
	return tmp
}

// MedalReorderDirectionValues returns a list of the values for MedalReorderDirection
func MedalReorderDirectionValues() []MedalReorderDirection {
	return []MedalReorderDirection{
		MedalReorderDirectionUp,
		MedalReorderDirectionDown,
	}
}

// String implements the Stringer interface.
func (x MedalReorderDirection) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x MedalReorderDirection) IsValid() bool {
	_, err := ParseMedalReorderDirection(string(x))
	return err == nil
}

var _MedalReorderDirectionValue = map[string]MedalReorderDirection{
	"up":   MedalReorderDirectionUp,
	"down": MedalReorderDirectionDown,
}

// ParseMedalReorderDirection attempts to convert a string to a MedalReorderDirection.
func ParseMedalReorderDirection(name string) (MedalReorderDirection, error) {
	if x, ok := _MedalReorderDirectionValue[name]; ok {
		return x, nil
	}
	return MedalReorderDirection(""), fmt.Errorf("%s is %w", name, ErrInvalidMedalReorderDirection)
}

// MustParseMedalReorderDirection converts a string to a MedalReorderDirection, and panics if is not valid.
func MustParseMedalReorderDirection(name string) MedalReorderDirection {
	val, err := ParseMedalReorderDirection(name)
	if err != nil {
		panic(err)
	}
	return val
}

func (x MedalReorderDirection) Ptr() *MedalReorderDirection {
	return &x
}

// MarshalText implements the text marshaller method.
func (x MedalReorderDirection) MarshalText() ([]byte, error) {
	return []byte(string(x)), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *MedalReorderDirection) UnmarshalText(text []byte) error {
	tmp, err := ParseMedalReorderDirection(string(text))
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

const (
	// MedalTypeNormal is a MedalType of type normal.
	// 黑
	MedalTypeNormal MedalType = "普通"
	// MedalTypeFine is a MedalType of type fine.
	// 蓝
	MedalTypeFine MedalType = "精良"
	// MedalTypeRare is a MedalType of type rare.
	// 紫
	MedalTypeRare MedalType = "稀有"
	// MedalTypeEpic is a MedalType of type epic.
	// 橙+略加粗
	MedalTypeEpic MedalType = "史诗"
	// MedalTypeLegendary is a MedalType of type legendary.
	// 金+加粗
	MedalTypeLegendary MedalType = "传说"
	// MedalTypeMythic is a MedalType of type mythic.
	// 更亮的金色
	MedalTypeMythic MedalType = "神话"
)

var ErrInvalidMedalType = fmt.Errorf("not a valid MedalType, try [%s]", strings.Join(_MedalTypeNames, ", "))

var _MedalTypeNames = []string{
	string(MedalTypeNormal),
	string(MedalTypeFine),
	string(MedalTypeRare),
	string(MedalTypeEpic),
	string(MedalTypeLegendary),
	string(MedalTypeMythic),
}

// MedalTypeNames returns a list of possible string values of MedalType.
func MedalTypeNames() []string {
	tmp := make([]string, len(_MedalTypeNames))
	copy(tmp, _MedalTypeNames)
	return tmp
}

// MedalTypeValues returns a list of the values for MedalType
func MedalTypeValues() []MedalType {
	return []MedalType{
		MedalTypeNormal,
		MedalTypeFine,
		MedalTypeRare,
		MedalTypeEpic,
		MedalTypeLegendary,
		MedalTypeMythic,
	}
}

// String implements the Stringer interface.
func (x MedalType) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x MedalType) IsValid() bool {
	_, err := ParseMedalType(string(x))
	return err == nil
}

var _MedalTypeValue = map[string]MedalType{
	"普通": MedalTypeNormal,
	"精良": MedalTypeFine,
	"稀有": MedalTypeRare,
	"史诗": MedalTypeEpic,
	"传说": MedalTypeLegendary,
	"神话": MedalTypeMythic,
}

// ParseMedalType attempts to convert a string to a MedalType.
func ParseMedalType(name string) (MedalType, error) {
	if x, ok := _MedalTypeValue[name]; ok {
		return x, nil
	}
	return MedalType(""), fmt.Errorf("%s is %w", name, ErrInvalidMedalType)
}

// MustParseMedalType converts a string to a MedalType, and panics if is not valid.
func MustParseMedalType(name string) MedalType {
	val, err := ParseMedalType(name)
	if err != nil {
		panic(err)
	}
	return val
}

func (x MedalType) Ptr() *MedalType {
	return &x
}

// MarshalText implements the text marshaller method.
func (x MedalType) MarshalText() ([]byte, error) {
	return []byte(string(x)), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *MedalType) UnmarshalText(text []byte) error {
	tmp, err := ParseMedalType(string(text))
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}
