// Code generated by go-enum DO NOT EDIT.
// Version:
// Revision:
// Build Date:
// Built By:

package types

import (
	"fmt"
	"strings"
)

const (
	// UserRoleNew is a UserRole of type new.
	UserRoleNew UserRole = "新手"
	// UserRoleVip is a UserRole of type vip.
	UserRoleVip UserRole = "会员"
	// UserRoleSvip is a UserRole of type svip.
	UserRoleSvip UserRole = "超级会员"
	// UserRolePolice is a UserRole of type police.
	UserRolePolice UserRole = "纪律委员"
	// UserRoleOp is a UserRole of type op.
	UserRoleOp UserRole = "OP"
	// UserRoleAdmin is a UserRole of type admin.
	UserRoleAdmin UserRole = "管理员"
)

var ErrInvalidUserRole = fmt.Errorf("not a valid UserRole, try [%s]", strings.Join(_UserRoleNames, ", "))

var _UserRoleNames = []string{
	string(UserRoleNew),
	string(UserRoleVip),
	string(UserRoleSvip),
	string(UserRolePolice),
	string(UserRoleOp),
	string(UserRoleAdmin),
}

// UserRoleNames returns a list of possible string values of UserRole.
func UserRoleNames() []string {
	tmp := make([]string, len(_UserRoleNames))
	copy(tmp, _UserRoleNames)
	return tmp
}

// UserRoleValues returns a list of the values for UserRole
func UserRoleValues() []UserRole {
	return []UserRole{
		UserRoleNew,
		UserRoleVip,
		UserRoleSvip,
		UserRolePolice,
		UserRoleOp,
		UserRoleAdmin,
	}
}

// String implements the Stringer interface.
func (x UserRole) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x UserRole) IsValid() bool {
	_, err := ParseUserRole(string(x))
	return err == nil
}

var _UserRoleValue = map[string]UserRole{
	"新手":   UserRoleNew,
	"会员":   UserRoleVip,
	"超级会员": UserRoleSvip,
	"纪律委员": UserRolePolice,
	"OP":   UserRoleOp,
	"管理员":  UserRoleAdmin,
}

// ParseUserRole attempts to convert a string to a UserRole.
func ParseUserRole(name string) (UserRole, error) {
	if x, ok := _UserRoleValue[name]; ok {
		return x, nil
	}
	return UserRole(""), fmt.Errorf("%s is %w", name, ErrInvalidUserRole)
}

// MustParseUserRole converts a string to a UserRole, and panics if is not valid.
func MustParseUserRole(name string) UserRole {
	val, err := ParseUserRole(name)
	if err != nil {
		panic(err)
	}
	return val
}

func (x UserRole) Ptr() *UserRole {
	return &x
}

// MarshalText implements the text marshaller method.
func (x UserRole) MarshalText() ([]byte, error) {
	return []byte(string(x)), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *UserRole) UnmarshalText(text []byte) error {
	tmp, err := ParseUserRole(string(text))
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}
