// Code generated by go-enum DO NOT EDIT.
// Version:
// Revision:
// Build Date:
// Built By:

package types

import (
	"fmt"
	"strings"
)

const (
	// ArticleShowInListYes is a ArticleShowInList of type Yes.
	// 是
	ArticleShowInListYes ArticleShowInList = iota + 1
	// ArticleShowInListNo is a ArticleShowInList of type No.
	// 否
	ArticleShowInListNo ArticleShowInList = iota + -1
)

var ErrInvalidArticleShowInList = fmt.Errorf("not a valid ArticleShowInList, try [%s]", strings.Join(_ArticleShowInListNames, ", "))

const _ArticleShowInListName = "yesno"

var _ArticleShowInListNames = []string{
	_ArticleShowInListName[0:3],
	_ArticleShowInListName[3:5],
}

// ArticleShowInListNames returns a list of possible string values of ArticleShowInList.
func ArticleShowInListNames() []string {
	tmp := make([]string, len(_ArticleShowInListNames))
	copy(tmp, _ArticleShowInListNames)
	return tmp
}

// ArticleShowInListValues returns a list of the values for ArticleShowInList
func ArticleShowInListValues() []ArticleShowInList {
	return []ArticleShowInList{
		ArticleShowInListYes,
		ArticleShowInListNo,
	}
}

var _ArticleShowInListMap = map[ArticleShowInList]string{
	ArticleShowInListYes: _ArticleShowInListName[0:3],
	ArticleShowInListNo:  _ArticleShowInListName[3:5],
}

// String implements the Stringer interface.
func (x ArticleShowInList) String() string {
	if str, ok := _ArticleShowInListMap[x]; ok {
		return str
	}
	return fmt.Sprintf("ArticleShowInList(%d)", x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x ArticleShowInList) IsValid() bool {
	_, ok := _ArticleShowInListMap[x]
	return ok
}

var _ArticleShowInListValue = map[string]ArticleShowInList{
	_ArticleShowInListName[0:3]: ArticleShowInListYes,
	_ArticleShowInListName[3:5]: ArticleShowInListNo,
}

// ParseArticleShowInList attempts to convert a string to a ArticleShowInList.
func ParseArticleShowInList(name string) (ArticleShowInList, error) {
	if x, ok := _ArticleShowInListValue[name]; ok {
		return x, nil
	}
	return ArticleShowInList(0), fmt.Errorf("%s is %w", name, ErrInvalidArticleShowInList)
}

// MustParseArticleShowInList converts a string to a ArticleShowInList, and panics if is not valid.
func MustParseArticleShowInList(name string) ArticleShowInList {
	val, err := ParseArticleShowInList(name)
	if err != nil {
		panic(err)
	}
	return val
}

func (x ArticleShowInList) Ptr() *ArticleShowInList {
	return &x
}

const (
	// ArticleTypeNormal is a ArticleType of type Normal.
	// 普通帖子
	ArticleTypeNormal ArticleType = iota
	// ArticleTypePrivate is a ArticleType of type Private.
	// 机要
	ArticleTypePrivate
	// ArticleTypeBroadcast is a ArticleType of type Broadcast.
	// 同城广播
	ArticleTypeBroadcast
	// ArticleTypeThought is a ArticleType of type Thought.
	// 思绪
	ArticleTypeThought
	// ArticleTypeQuestion is a ArticleType of type Question.
	// 问题
	ArticleTypeQuestion ArticleType = iota + 1
)

var ErrInvalidArticleType = fmt.Errorf("not a valid ArticleType, try [%s]", strings.Join(_ArticleTypeNames, ", "))

const _ArticleTypeName = "normalprivatebroadcastthoughtquestion"

var _ArticleTypeNames = []string{
	_ArticleTypeName[0:6],
	_ArticleTypeName[6:13],
	_ArticleTypeName[13:22],
	_ArticleTypeName[22:29],
	_ArticleTypeName[29:37],
}

// ArticleTypeNames returns a list of possible string values of ArticleType.
func ArticleTypeNames() []string {
	tmp := make([]string, len(_ArticleTypeNames))
	copy(tmp, _ArticleTypeNames)
	return tmp
}

// ArticleTypeValues returns a list of the values for ArticleType
func ArticleTypeValues() []ArticleType {
	return []ArticleType{
		ArticleTypeNormal,
		ArticleTypePrivate,
		ArticleTypeBroadcast,
		ArticleTypeThought,
		ArticleTypeQuestion,
	}
}

var _ArticleTypeMap = map[ArticleType]string{
	ArticleTypeNormal:    _ArticleTypeName[0:6],
	ArticleTypePrivate:   _ArticleTypeName[6:13],
	ArticleTypeBroadcast: _ArticleTypeName[13:22],
	ArticleTypeThought:   _ArticleTypeName[22:29],
	ArticleTypeQuestion:  _ArticleTypeName[29:37],
}

// String implements the Stringer interface.
func (x ArticleType) String() string {
	if str, ok := _ArticleTypeMap[x]; ok {
		return str
	}
	return fmt.Sprintf("ArticleType(%d)", x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x ArticleType) IsValid() bool {
	_, ok := _ArticleTypeMap[x]
	return ok
}

var _ArticleTypeValue = map[string]ArticleType{
	_ArticleTypeName[0:6]:   ArticleTypeNormal,
	_ArticleTypeName[6:13]:  ArticleTypePrivate,
	_ArticleTypeName[13:22]: ArticleTypeBroadcast,
	_ArticleTypeName[22:29]: ArticleTypeThought,
	_ArticleTypeName[29:37]: ArticleTypeQuestion,
}

// ParseArticleType attempts to convert a string to a ArticleType.
func ParseArticleType(name string) (ArticleType, error) {
	if x, ok := _ArticleTypeValue[name]; ok {
		return x, nil
	}
	return ArticleType(0), fmt.Errorf("%s is %w", name, ErrInvalidArticleType)
}

// MustParseArticleType converts a string to a ArticleType, and panics if is not valid.
func MustParseArticleType(name string) ArticleType {
	val, err := ParseArticleType(name)
	if err != nil {
		panic(err)
	}
	return val
}

func (x ArticleType) Ptr() *ArticleType {
	return &x
}
