// Code generated by go-enum DO NOT EDIT.
// Version:
// Revision:
// Build Date:
// Built By:

package types

import (
	"fmt"
	"strings"
)

const (
	// BadgeWayTop is a BadgeWay of type top.
	// 从上到下
	BadgeWayTop BadgeWay = "top"
	// BadgeWayBottom is a BadgeWay of type bottom.
	// 从下到上
	BadgeWayBottom BadgeWay = "bottom"
	// BadgeWayLeft is a BadgeWay of type left.
	// 从左到右
	BadgeWayLeft BadgeWay = "left"
	// BadgeWayRight is a BadgeWay of type right.
	// 从右到左
	BadgeWayRight BadgeWay = "right"
	// BadgeWayTopLeft is a BadgeWay of type top-left.
	// 从左上到右下
	BadgeWayTopLeft BadgeWay = "top-left"
	// BadgeWayTopRight is a BadgeWay of type top-right.
	// 从右上到左下
	BadgeWayTopRight BadgeWay = "top-right"
	// BadgeWayBottomLeft is a BadgeWay of type bottom-left.
	// 从左下到右上
	BadgeWayBottomLeft BadgeWay = "bottom-left"
	// BadgeWayBottomRight is a BadgeWay of type bottom-right.
	// 从右下到左上
	BadgeWayBottomRight BadgeWay = "bottom-right"
)

var ErrInvalidBadgeWay = fmt.Errorf("not a valid BadgeWay, try [%s]", strings.Join(_BadgeWayNames, ", "))

var _BadgeWayNames = []string{
	string(BadgeWayTop),
	string(BadgeWayBottom),
	string(BadgeWayLeft),
	string(BadgeWayRight),
	string(BadgeWayTopLeft),
	string(BadgeWayTopRight),
	string(BadgeWayBottomLeft),
	string(BadgeWayBottomRight),
}

// BadgeWayNames returns a list of possible string values of BadgeWay.
func BadgeWayNames() []string {
	tmp := make([]string, len(_BadgeWayNames))
	copy(tmp, _BadgeWayNames)
	return tmp
}

// BadgeWayValues returns a list of the values for BadgeWay
func BadgeWayValues() []BadgeWay {
	return []BadgeWay{
		BadgeWayTop,
		BadgeWayBottom,
		BadgeWayLeft,
		BadgeWayRight,
		BadgeWayTopLeft,
		BadgeWayTopRight,
		BadgeWayBottomLeft,
		BadgeWayBottomRight,
	}
}

// String implements the Stringer interface.
func (x BadgeWay) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x BadgeWay) IsValid() bool {
	_, err := ParseBadgeWay(string(x))
	return err == nil
}

var _BadgeWayValue = map[string]BadgeWay{
	"top":          BadgeWayTop,
	"bottom":       BadgeWayBottom,
	"left":         BadgeWayLeft,
	"right":        BadgeWayRight,
	"top-left":     BadgeWayTopLeft,
	"top-right":    BadgeWayTopRight,
	"bottom-left":  BadgeWayBottomLeft,
	"bottom-right": BadgeWayBottomRight,
}

// ParseBadgeWay attempts to convert a string to a BadgeWay.
func ParseBadgeWay(name string) (BadgeWay, error) {
	if x, ok := _BadgeWayValue[name]; ok {
		return x, nil
	}
	return BadgeWay(""), fmt.Errorf("%s is %w", name, ErrInvalidBadgeWay)
}

// MustParseBadgeWay converts a string to a BadgeWay, and panics if is not valid.
func MustParseBadgeWay(name string) BadgeWay {
	val, err := ParseBadgeWay(name)
	if err != nil {
		panic(err)
	}
	return val
}

func (x BadgeWay) Ptr() *BadgeWay {
	return &x
}

// MarshalText implements the text marshaller method.
func (x BadgeWay) MarshalText() ([]byte, error) {
	return []byte(string(x)), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *BadgeWay) UnmarshalText(text []byte) error {
	tmp, err := ParseBadgeWay(string(text))
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

const (
	// MedalReorderDirectionUp is a MedalReorderDirection of type up.
	// 上移
	MedalReorderDirectionUp MedalReorderDirection = "up"
	// MedalReorderDirectionDown is a MedalReorderDirection of type down.
	// 下移
	MedalReorderDirectionDown MedalReorderDirection = "down"
)

var ErrInvalidMedalReorderDirection = fmt.Errorf("not a valid MedalReorderDirection, try [%s]", strings.Join(_MedalReorderDirectionNames, ", "))

var _MedalReorderDirectionNames = []string{
	string(MedalReorderDirectionUp),
	string(MedalReorderDirectionDown),
}

// MedalReorderDirectionNames returns a list of possible string values of MedalReorderDirection.
func MedalReorderDirectionNames() []string {
	tmp := make([]string, len(_MedalReorderDirectionNames))
	copy(tmp, _MedalReorderDirectionNames)
	return tmp
}

// MedalReorderDirectionValues returns a list of the values for MedalReorderDirection
func MedalReorderDirectionValues() []MedalReorderDirection {
	return []MedalReorderDirection{
		MedalReorderDirectionUp,
		MedalReorderDirectionDown,
	}
}

// String implements the Stringer interface.
func (x MedalReorderDirection) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x MedalReorderDirection) IsValid() bool {
	_, err := ParseMedalReorderDirection(string(x))
	return err == nil
}

var _MedalReorderDirectionValue = map[string]MedalReorderDirection{
	"up":   MedalReorderDirectionUp,
	"down": MedalReorderDirectionDown,
}

// ParseMedalReorderDirection attempts to convert a string to a MedalReorderDirection.
func ParseMedalReorderDirection(name string) (MedalReorderDirection, error) {
	if x, ok := _MedalReorderDirectionValue[name]; ok {
		return x, nil
	}
	return MedalReorderDirection(""), fmt.Errorf("%s is %w", name, ErrInvalidMedalReorderDirection)
}

// MustParseMedalReorderDirection converts a string to a MedalReorderDirection, and panics if is not valid.
func MustParseMedalReorderDirection(name string) MedalReorderDirection {
	val, err := ParseMedalReorderDirection(name)
	if err != nil {
		panic(err)
	}
	return val
}

func (x MedalReorderDirection) Ptr() *MedalReorderDirection {
	return &x
}

// MarshalText implements the text marshaller method.
func (x MedalReorderDirection) MarshalText() ([]byte, error) {
	return []byte(string(x)), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *MedalReorderDirection) UnmarshalText(text []byte) error {
	tmp, err := ParseMedalReorderDirection(string(text))
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

const (
	// MedalTypeNormal is a MedalType of type normal.
	// 黑
	MedalTypeNormal MedalType = "普通"
	// MedalTypeFine is a MedalType of type fine.
	// 蓝
	MedalTypeFine MedalType = "精良"
	// MedalTypeRare is a MedalType of type rare.
	// 紫
	MedalTypeRare MedalType = "稀有"
	// MedalTypeEpic is a MedalType of type epic.
	// 橙+略加粗
	MedalTypeEpic MedalType = "史诗"
	// MedalTypeLegendary is a MedalType of type legendary.
	// 金+加粗
	MedalTypeLegendary MedalType = "传说"
	// MedalTypeMythic is a MedalType of type mythic.
	// 更亮的金色
	MedalTypeMythic MedalType = "神话"
	// MedalTypeFinite is a MedalType of type finite.
	MedalTypeFinite MedalType = "限定"
)

var ErrInvalidMedalType = fmt.Errorf("not a valid MedalType, try [%s]", strings.Join(_MedalTypeNames, ", "))

var _MedalTypeNames = []string{
	string(MedalTypeNormal),
	string(MedalTypeFine),
	string(MedalTypeRare),
	string(MedalTypeEpic),
	string(MedalTypeLegendary),
	string(MedalTypeMythic),
	string(MedalTypeFinite),
}

// MedalTypeNames returns a list of possible string values of MedalType.
func MedalTypeNames() []string {
	tmp := make([]string, len(_MedalTypeNames))
	copy(tmp, _MedalTypeNames)
	return tmp
}

// MedalTypeValues returns a list of the values for MedalType
func MedalTypeValues() []MedalType {
	return []MedalType{
		MedalTypeNormal,
		MedalTypeFine,
		MedalTypeRare,
		MedalTypeEpic,
		MedalTypeLegendary,
		MedalTypeMythic,
		MedalTypeFinite,
	}
}

// String implements the Stringer interface.
func (x MedalType) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x MedalType) IsValid() bool {
	_, err := ParseMedalType(string(x))
	return err == nil
}

var _MedalTypeValue = map[string]MedalType{
	"普通": MedalTypeNormal,
	"精良": MedalTypeFine,
	"稀有": MedalTypeRare,
	"史诗": MedalTypeEpic,
	"传说": MedalTypeLegendary,
	"神话": MedalTypeMythic,
	"限定": MedalTypeFinite,
}

// ParseMedalType attempts to convert a string to a MedalType.
func ParseMedalType(name string) (MedalType, error) {
	if x, ok := _MedalTypeValue[name]; ok {
		return x, nil
	}
	return MedalType(""), fmt.Errorf("%s is %w", name, ErrInvalidMedalType)
}

// MustParseMedalType converts a string to a MedalType, and panics if is not valid.
func MustParseMedalType(name string) MedalType {
	val, err := ParseMedalType(name)
	if err != nil {
		panic(err)
	}
	return val
}

func (x MedalType) Ptr() *MedalType {
	return &x
}

// MarshalText implements the text marshaller method.
func (x MedalType) MarshalText() ([]byte, error) {
	return []byte(string(x)), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *MedalType) UnmarshalText(text []byte) error {
	tmp, err := ParseMedalType(string(text))
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}
