// Code generated by go-enum DO NOT EDIT.
// Version:
// Revision:
// Build Date:
// Built By:

package types

import (
	"fmt"
	"strings"
)

const (
	// ArticleIsGoodArticleYes is a ArticleIsGoodArticle of type yes.
	// 好文
	ArticleIsGoodArticleYes ArticleIsGoodArticle = "yes"
	// ArticleIsGoodArticleNo is a ArticleIsGoodArticle of type no.
	// 随便写写
	ArticleIsGoodArticleNo ArticleIsGoodArticle = "no"
)

var ErrInvalidArticleIsGoodArticle = fmt.Errorf("not a valid ArticleIsGoodArticle, try [%s]", strings.Join(_ArticleIsGoodArticleNames, ", "))

var _ArticleIsGoodArticleNames = []string{
	string(ArticleIsGoodArticleYes),
	string(ArticleIsGoodArticleNo),
}

// ArticleIsGoodArticleNames returns a list of possible string values of ArticleIsGoodArticle.
func ArticleIsGoodArticleNames() []string {
	tmp := make([]string, len(_ArticleIsGoodArticleNames))
	copy(tmp, _ArticleIsGoodArticleNames)
	return tmp
}

// ArticleIsGoodArticleValues returns a list of the values for ArticleIsGoodArticle
func ArticleIsGoodArticleValues() []ArticleIsGoodArticle {
	return []ArticleIsGoodArticle{
		ArticleIsGoodArticleYes,
		ArticleIsGoodArticleNo,
	}
}

// String implements the Stringer interface.
func (x ArticleIsGoodArticle) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x ArticleIsGoodArticle) IsValid() bool {
	_, err := ParseArticleIsGoodArticle(string(x))
	return err == nil
}

var _ArticleIsGoodArticleValue = map[string]ArticleIsGoodArticle{
	"yes": ArticleIsGoodArticleYes,
	"no":  ArticleIsGoodArticleNo,
}

// ParseArticleIsGoodArticle attempts to convert a string to a ArticleIsGoodArticle.
func ParseArticleIsGoodArticle(name string) (ArticleIsGoodArticle, error) {
	if x, ok := _ArticleIsGoodArticleValue[name]; ok {
		return x, nil
	}
	return ArticleIsGoodArticle(""), fmt.Errorf("%s is %w", name, ErrInvalidArticleIsGoodArticle)
}

// MustParseArticleIsGoodArticle converts a string to a ArticleIsGoodArticle, and panics if is not valid.
func MustParseArticleIsGoodArticle(name string) ArticleIsGoodArticle {
	val, err := ParseArticleIsGoodArticle(name)
	if err != nil {
		panic(err)
	}
	return val
}

func (x ArticleIsGoodArticle) Ptr() *ArticleIsGoodArticle {
	return &x
}

const (
	// ArticleShowInListYes is a ArticleShowInList of type Yes.
	// 是
	ArticleShowInListYes ArticleShowInList = iota + 1
	// ArticleShowInListNo is a ArticleShowInList of type No.
	// 否
	ArticleShowInListNo ArticleShowInList = iota + -1
)

var ErrInvalidArticleShowInList = fmt.Errorf("not a valid ArticleShowInList, try [%s]", strings.Join(_ArticleShowInListNames, ", "))

const _ArticleShowInListName = "yesno"

var _ArticleShowInListNames = []string{
	_ArticleShowInListName[0:3],
	_ArticleShowInListName[3:5],
}

// ArticleShowInListNames returns a list of possible string values of ArticleShowInList.
func ArticleShowInListNames() []string {
	tmp := make([]string, len(_ArticleShowInListNames))
	copy(tmp, _ArticleShowInListNames)
	return tmp
}

// ArticleShowInListValues returns a list of the values for ArticleShowInList
func ArticleShowInListValues() []ArticleShowInList {
	return []ArticleShowInList{
		ArticleShowInListYes,
		ArticleShowInListNo,
	}
}

var _ArticleShowInListMap = map[ArticleShowInList]string{
	ArticleShowInListYes: _ArticleShowInListName[0:3],
	ArticleShowInListNo:  _ArticleShowInListName[3:5],
}

// String implements the Stringer interface.
func (x ArticleShowInList) String() string {
	if str, ok := _ArticleShowInListMap[x]; ok {
		return str
	}
	return fmt.Sprintf("ArticleShowInList(%d)", x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x ArticleShowInList) IsValid() bool {
	_, ok := _ArticleShowInListMap[x]
	return ok
}

var _ArticleShowInListValue = map[string]ArticleShowInList{
	_ArticleShowInListName[0:3]: ArticleShowInListYes,
	_ArticleShowInListName[3:5]: ArticleShowInListNo,
}

// ParseArticleShowInList attempts to convert a string to a ArticleShowInList.
func ParseArticleShowInList(name string) (ArticleShowInList, error) {
	if x, ok := _ArticleShowInListValue[name]; ok {
		return x, nil
	}
	return ArticleShowInList(0), fmt.Errorf("%s is %w", name, ErrInvalidArticleShowInList)
}

// MustParseArticleShowInList converts a string to a ArticleShowInList, and panics if is not valid.
func MustParseArticleShowInList(name string) ArticleShowInList {
	val, err := ParseArticleShowInList(name)
	if err != nil {
		panic(err)
	}
	return val
}

func (x ArticleShowInList) Ptr() *ArticleShowInList {
	return &x
}

const (
	// ArticleStatementNone is a ArticleStatement of type None.
	// 无声明
	ArticleStatementNone ArticleStatement = iota
	// ArticleStatementAi is a ArticleStatement of type Ai.
	// 包含AI辅助创作
	ArticleStatementAi
	// ArticleStatementSpoiler is a ArticleStatement of type Spoiler.
	// 包含剧透
	ArticleStatementSpoiler
	// ArticleStatementFiction is a ArticleStatement of type Fiction.
	// 虚构演绎，仅供娱乐
	ArticleStatementFiction
)

var ErrInvalidArticleStatement = fmt.Errorf("not a valid ArticleStatement, try [%s]", strings.Join(_ArticleStatementNames, ", "))

const _ArticleStatementName = "noneaispoilerfiction"

var _ArticleStatementNames = []string{
	_ArticleStatementName[0:4],
	_ArticleStatementName[4:6],
	_ArticleStatementName[6:13],
	_ArticleStatementName[13:20],
}

// ArticleStatementNames returns a list of possible string values of ArticleStatement.
func ArticleStatementNames() []string {
	tmp := make([]string, len(_ArticleStatementNames))
	copy(tmp, _ArticleStatementNames)
	return tmp
}

// ArticleStatementValues returns a list of the values for ArticleStatement
func ArticleStatementValues() []ArticleStatement {
	return []ArticleStatement{
		ArticleStatementNone,
		ArticleStatementAi,
		ArticleStatementSpoiler,
		ArticleStatementFiction,
	}
}

var _ArticleStatementMap = map[ArticleStatement]string{
	ArticleStatementNone:    _ArticleStatementName[0:4],
	ArticleStatementAi:      _ArticleStatementName[4:6],
	ArticleStatementSpoiler: _ArticleStatementName[6:13],
	ArticleStatementFiction: _ArticleStatementName[13:20],
}

// String implements the Stringer interface.
func (x ArticleStatement) String() string {
	if str, ok := _ArticleStatementMap[x]; ok {
		return str
	}
	return fmt.Sprintf("ArticleStatement(%d)", x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x ArticleStatement) IsValid() bool {
	_, ok := _ArticleStatementMap[x]
	return ok
}

var _ArticleStatementValue = map[string]ArticleStatement{
	_ArticleStatementName[0:4]:   ArticleStatementNone,
	_ArticleStatementName[4:6]:   ArticleStatementAi,
	_ArticleStatementName[6:13]:  ArticleStatementSpoiler,
	_ArticleStatementName[13:20]: ArticleStatementFiction,
}

// ParseArticleStatement attempts to convert a string to a ArticleStatement.
func ParseArticleStatement(name string) (ArticleStatement, error) {
	if x, ok := _ArticleStatementValue[name]; ok {
		return x, nil
	}
	return ArticleStatement(0), fmt.Errorf("%s is %w", name, ErrInvalidArticleStatement)
}

// MustParseArticleStatement converts a string to a ArticleStatement, and panics if is not valid.
func MustParseArticleStatement(name string) ArticleStatement {
	val, err := ParseArticleStatement(name)
	if err != nil {
		panic(err)
	}
	return val
}

func (x ArticleStatement) Ptr() *ArticleStatement {
	return &x
}

const (
	// ArticleTypeNormal is a ArticleType of type Normal.
	// 普通帖子
	ArticleTypeNormal ArticleType = iota
	// ArticleTypePrivate is a ArticleType of type Private.
	// 机要
	ArticleTypePrivate
	// ArticleTypeBroadcast is a ArticleType of type Broadcast.
	// 同城广播
	ArticleTypeBroadcast
	// ArticleTypeThought is a ArticleType of type Thought.
	// 思绪
	ArticleTypeThought
	// ArticleTypeQuestion is a ArticleType of type Question.
	// 问题
	ArticleTypeQuestion ArticleType = iota + 1
	// ArticleTypeLong is a ArticleType of type Long.
	// 长文
	ArticleTypeLong
)

var ErrInvalidArticleType = fmt.Errorf("not a valid ArticleType, try [%s]", strings.Join(_ArticleTypeNames, ", "))

const _ArticleTypeName = "normalprivatebroadcastthoughtquestionlong"

var _ArticleTypeNames = []string{
	_ArticleTypeName[0:6],
	_ArticleTypeName[6:13],
	_ArticleTypeName[13:22],
	_ArticleTypeName[22:29],
	_ArticleTypeName[29:37],
	_ArticleTypeName[37:41],
}

// ArticleTypeNames returns a list of possible string values of ArticleType.
func ArticleTypeNames() []string {
	tmp := make([]string, len(_ArticleTypeNames))
	copy(tmp, _ArticleTypeNames)
	return tmp
}

// ArticleTypeValues returns a list of the values for ArticleType
func ArticleTypeValues() []ArticleType {
	return []ArticleType{
		ArticleTypeNormal,
		ArticleTypePrivate,
		ArticleTypeBroadcast,
		ArticleTypeThought,
		ArticleTypeQuestion,
		ArticleTypeLong,
	}
}

var _ArticleTypeMap = map[ArticleType]string{
	ArticleTypeNormal:    _ArticleTypeName[0:6],
	ArticleTypePrivate:   _ArticleTypeName[6:13],
	ArticleTypeBroadcast: _ArticleTypeName[13:22],
	ArticleTypeThought:   _ArticleTypeName[22:29],
	ArticleTypeQuestion:  _ArticleTypeName[29:37],
	ArticleTypeLong:      _ArticleTypeName[37:41],
}

// String implements the Stringer interface.
func (x ArticleType) String() string {
	if str, ok := _ArticleTypeMap[x]; ok {
		return str
	}
	return fmt.Sprintf("ArticleType(%d)", x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x ArticleType) IsValid() bool {
	_, ok := _ArticleTypeMap[x]
	return ok
}

var _ArticleTypeValue = map[string]ArticleType{
	_ArticleTypeName[0:6]:   ArticleTypeNormal,
	_ArticleTypeName[6:13]:  ArticleTypePrivate,
	_ArticleTypeName[13:22]: ArticleTypeBroadcast,
	_ArticleTypeName[22:29]: ArticleTypeThought,
	_ArticleTypeName[29:37]: ArticleTypeQuestion,
	_ArticleTypeName[37:41]: ArticleTypeLong,
}

// ParseArticleType attempts to convert a string to a ArticleType.
func ParseArticleType(name string) (ArticleType, error) {
	if x, ok := _ArticleTypeValue[name]; ok {
		return x, nil
	}
	return ArticleType(0), fmt.Errorf("%s is %w", name, ErrInvalidArticleType)
}

// MustParseArticleType converts a string to a ArticleType, and panics if is not valid.
func MustParseArticleType(name string) ArticleType {
	val, err := ParseArticleType(name)
	if err != nil {
		panic(err)
	}
	return val
}

func (x ArticleType) Ptr() *ArticleType {
	return &x
}
